### ISSUE TITLE
🐛 [User Issue] - Books POS screen now showing entirely - pay/discount buttons are not all appearing.

### ISSUE THREAD

**Issue by uc77** [frappe/books#1001]
### Expected Behavior

Not sure if it's my resolution or something else. However, POS screen should entirely display.

### Current Behavior

POS screen not fully displaying. More specifically, the discount+pay buttons are half showing. See image.
![image](https://github.com/user-attachments/assets/cd6ec988-06f8-4409-b73b-68535105a791)

### Steps to Reproduce

1. Frappe Books
2. Settings > Enable POS
3. Access "POS" screen from left side menu.
4. Et voila.

### FrappeBooks Version

0.23.0

### Path or Feature name

/pos

### Country

EN-US

### Language

English

### OS

Windows 11

### Additional OS Info

Microsoft Windows 11 Home Edition

**Comment by akshayitzme** [comment]
@uc77 Could you specify your screen resolution? So I can try replicating it.

**Comment by uc77** [comment]
![image](https://github.com/user-attachments/assets/f38484ba-9b42-432b-a5d3-2edecf27ba4d)

**Comment by uc77** [comment]
I've decreased the Scale (was 300% as recommended) to 250% now.

![image](https://github.com/user-attachments/assets/e86e9ded-4911-4ce2-baee-c095dc7d3459)

It's better but now I need reading glasses :)

**Comment by uc77** [comment]
Thanks!
