### ISSUE TITLE
🐛 [Bug] - Frappe Books 0.24 | White blank screen after installing on Windows 11

### ISSUE THREAD

**Issue by uc77** [frappe/books#1014]
### Expected Behavior

To function correctly like 0.23.0 ( and prev. releases ) 

### Current Behavior

White screen after installing/running it.

![Frappe UI 1](https://github.com/user-attachments/assets/095a5b35-3b74-44d7-b945-0949054418df)

We thought this was because we had .23.0 already on our test system (Windows11). So, we uninstalled .23 and then fresh installed .24 and we got the white screen of death ⚪ .

### Steps to Reproduce

1. Install 0.24.0 exe (windows ver)
2. Run it
3. Boom - You get a white screen

### FrappeBooks Version

0.24.0

### Path or Feature name

Application

### Country

US

### Language

EN

### OS

Windows 11

### Additional OS Info

Home Edition

**Comment by uc77** [comment]
@rmehta @AbleKSaju

**Comment by mertaphor** [comment]
Same problem.

**Comment by uc77** [comment]
Screen shot added to issue. We've also downloaded FrappeBooks runnable exe and not setup to make sure issue is not because of the already running v0.23.

Same issue.

**Comment by akshayitzme** [comment]
Thank you for reporting the issue. A release containing the fix will be out in the coming days.

**Comment by uc77** [comment]
Thanks @akshayitzme !

**Comment by hawilix** [comment]
Same Problem ....

**Comment by akshayitzme** [comment]
fixed in [v0.24.1](https://github.com/frappe/books/releases/tag/v0.24.1)

**Comment by uc77** [comment]
Thanks guys!!

**Comment by uc77** [comment]
Confirmed it's been resolved!
