### ISSUE TITLE
💡 Frappe Books 0.24 | Arabic translation is not completed .. How to Fix This ???? 

### ISSUE THREAD

**Issue by hawilix** [frappe/books#1016]
### Summary

The arabic translation in Frappe Books 0.24 is not completed or has Inaccurate translation.
Can any one do it OR Giude me to make it Profficional ?
The file ar.csv is locating in Translation folder

### What problem are you trying to solve?

The arabic translation in Frappe Books 0.24

### Basic Example

as you can see ....
Something done and other not

Action,,
Active,,
"Add Account","إضافة حساب",
"Add Customers","إضافة العملاء",
"Add Group","إضافة مجموعة",
"Add Items","إضافة عناصر",
"Add Row","إضافة صف",
"Add Suppliers","إضافة الموردين",
"Add Taxes","إضافة ضرائب",
"Add a few customers to create your first sales invoice",,
"Add a few suppliers to create your first purchase invoice",,
"Add a filter","إضافة تصفية",
"Add a remark",,
"Add attachment","  أضف مرفق",
"Add invoice terms",,
"Add products or services that you buy from your suppliers",,
"Add products or services that you sell to your customers",,
"Add transfer terms",,
"Add'l Discounts",,
"Additional ${0} Serial Numbers required for ${1} quantity of ${2}.",,
"Additional quantity (${0}) required${1} to make outward transfer of item ${2} from ${3} on ${4}",,
Address,العنوان,
"Address Display","عرض العنوان",
"Address Line 1","سطر العنوان 1",
"Address Line 2","سطر العنوان 2",
"Address Name",,
"Administrative Expenses","مصاريف إدارية",
All,,

### Drawbacks

Failure to complete the translation correctly for any language (Arabic in this example) will deprive a large group of users who are eager to use this program, which will affect the continuous upgrade process.

**Comment by akshayitzme** [comment]
You can take a look at the following guide to contribute translations.

ref: [Contributing-Translations](https://github.com/frappe/books/wiki/Contributing-Translations)

Feel free to drop your doubts here.
