### ISSUE TITLE
Error in sql: commit

### ISSUE THREAD

**Issue by snawar92** [frappe/books#102]
i just installed app then run it , it asked db location after that it stuck on "Setup your organization"
page and there is error in log     "Error in sql: commit" i am trying to configure this app on mac

**Comment by karantkiruba** [comment]
Hi friend, Have you resolved the issue?

**Comment by snawar92** [comment]
no still facing the issue

**Comment by netchampfaris** [comment]
@snawar92 Hey, did you try this on the latest version again? That issue is fixed now.
