### ISSUE TITLE
Inventory not reflected properly with Accountings

### ISSUE THREAD

**Issue by jahidhsn002** [frappe/books#1034]
<h2>I think these are some bugs</h2>
1) Stock Movement not change Balance sheet <br/>
2) Incurrect COGS addition for basic menufecturing standpoint like tomatoo farm <br/>
3) On sales invoice always warns about not enough stock

<h2>Steps to Reproduce</h2>
After Stock Movement Type Manufacture entry Balance sheet does not reflect Stock In Hand value ... no changes in balance sheet ... <br/>
Also do not enter anything on COGS accont ... Only cogs entry is added on shipment and that is equal to shiped finished product value ...

![Screenshot 2024-11-26 152012](https://github.com/user-attachments/assets/6d848dc2-7d16-491e-90a7-cd9d7f67f669)
![Screenshot 2024-11-26 151938](https://github.com/user-attachments/assets/36759507-80ea-43b3-9932-028f82705d72)

<h2>Info</h2>

**Version**: `0.24.1`
**Platform**: `win32`
**Path**: `/report/StockBalance`
**Language**: `-`
**Country**: `bd`

**Comment by jahidhsn002** [comment]
![image](https://github.com/user-attachments/assets/6adbc5ab-c7d9-4735-8f7a-28d72c00899d)

Finally got why COGS transection was wrong . In Menufecturing all the froms should be equal to all the to's ... Still Insufficient quantity error remains ..

**Comment by akshayitzme** [comment]
Closing this as the Validation Error issue is fixed in #1047
