### ISSUE TITLE
🐛 [Bug] - <title>Wrong message"the following item has insufficient quantity for shipment"

### ISSUE THREAD

**Issue by mohammadmagdyhamo** [frappe/books#1038]
### Expected Behavior

Hello there all

The books app gives a message sometimes for items when making a sales invoice on a specific date saying: "the following item has insufficient quantity for shipment", though the stock inventory shows clearly that there is stock on that date

### Current Behavior

wrong message

### Steps to Reproduce

make a sales invoice for an item

### FrappeBooks Version

0.24.1

### Path or Feature name

sales invoice

### Country

Egypt

### Language

English

### OS

Windows 10

**Comment by ableksaju** [comment]
I am unable to reproduce this issue. Could you please confirm if the stock was available on the date the shipment or sales invoice was created?

**Comment by mohammadmagdyhamo** [comment]
Yes, its confirmed. It happened with multiple invoices

**Comment by mohammadmagdyhamo** [comment]
hello there
I faced the issue again today, I saved the invoice but not submitted it yet and waiting. an item only came once with stock 1 and never sold. So current stock is 1 and I face also this warning ""The following item has insufficient quantity for shipment" : Item name (0)
What should I do ?
