### ISSUE TITLE
Frappe Books: User Testing Issues

### ISSUE THREAD

**Issue by umairsy** [frappe/books#104]
### Database Won't be understanding for User

<img width="583" alt="Screenshot 2019-12-12 at 12 45 13 PM" src="https://user-images.githubusercontent.com/910238/70690863-a6340a80-1cdd-11ea-82c7-ecb38b36315f.png">

###  Fiscal Year start and end date should be 1/4/YYYY and 31/3/YYYY+1

<img width="571" alt="Screenshot 2019-12-12 at 12 49 36 PM" src="https://user-images.githubusercontent.com/910238/70691096-4427d500-1cde-11ea-87bd-04f2fd0433c5.png">

### List View - Empty state and prominent Primary action

<img width="1192" alt="Screenshot 2019-12-12 at 12 52 15 PM" src="https://user-images.githubusercontent.com/910238/70691245-9a951380-1cde-11ea-8d0c-dd8b896dbd4d.png">

### List view result - Differentiation in select value and next action (like Create)

<img width="335" alt="Screenshot 2019-12-12 at 12 53 02 PM" src="https://user-images.githubusercontent.com/910238/70691322-c0221d00-1cde-11ea-867f-77bf012466c2.png">

### Navigation 

from transaction to Master view (side bar) doesn't convey on which form to act. Perhaps if side bar is visible, then main form should be frozen. Mainly, providing one action point/form. Side bar is nice though.

<img width="1192" alt="Screenshot 2019-12-12 at 12 54 06 PM" src="https://user-images.githubusercontent.com/910238/70691403-06777c00-1cdf-11ea-873a-72c487056d9a.png">

### UoM:

Call it Unit or Nos. Not "No"

###  Item - Default Expense:

Don't show Stock Received but not Billed Account.

<img width="544" alt="Screenshot 2019-12-12 at 12 56 34 PM" src="https://user-images.githubusercontent.com/910238/70691533-48a0bd80-1cdf-11ea-94e0-e4ee8dad7076.png">

### item Rate fetch

Steps:
1. New Invoice
2. New item (with price)
3. Back to invoice > Select items

Item Rate not fetched

<img width="626" alt="Screenshot 2019-12-12 at 12 57 53 PM" src="https://user-images.githubusercontent.com/910238/70691590-7554d500-1cdf-11ea-954c-c6c923ff55d1.png">

### Invoice Qty

Set 1 by default

### Sales Invoice - Next Actions

Can we should button right away?

![image](https://user-images.githubusercontent.com/910238/70691689-b1883580-1cdf-11ea-8f5e-a6745fe07da8.png)

### Terms in Invoice

Provide text editor field (could be set as default?) for terms.

### Invoice Header

1. Isn't intuitive that Company Name should be part of "Letter Head". Give it 2/3 space?
2. Too much space for Phone. May append below address? 1/3 space.

![image](https://user-images.githubusercontent.com/910238/70691960-615da300-1ce0-11ea-9a58-1728f9d1fcc9.png)

### Dashboard not updated after invoice creation

![image](https://user-images.githubusercontent.com/910238/70692018-7df9db00-1ce0-11ea-8b81-5ba4743e2b1e.png)

### Haven't located Chart of Accounts as yet!!

Provide a link for Chart of Accounts view in left bar. It's beautiful and should be showcased. An option to create an Account from CoA view itself will be big win.

### Sales Invoice Paid?

While creating invoice, I didn't see any fields related to payment.

![image](https://user-images.githubusercontent.com/910238/70692262-f5c80580-1ce0-11ea-9dc7-43d76e993082.png)

### New Account creation issue

1. Why Balance field ?
2. If select parent account, we can append Root Type and Account Type of parent itself.
3. New form should indicate an area on clicking which form will become editable.

![image](https://user-images.githubusercontent.com/910238/70692589-a7ffcd00-1ce1-11ea-8365-4633090af4d5.png)

### No GL Posting against an Invoice

![image](https://user-images.githubusercontent.com/910238/70692647-c796f580-1ce1-11ea-9bcc-18e3fcb27bc9.png)

### Purchase Invoice

Can we call heading as Bill, since we are naming Bill in the left bar as well?

![image](https://user-images.githubusercontent.com/910238/70693234-12fdd380-1ce3-11ea-872f-25aba4d84a56.png)

**Comment by netchampfaris** [comment]
All of these issues are addressed in the latest update.
