### ISSUE TITLE
Bug , 0.25 consolidate/hide columns button check but no check in reports

### ISSUE THREAD

**Issue by mohammadmagdyhamo** [frappe/books#1058]
### Expected Behavior

When you consolidate/hide the numbers in all reports, you can check but you cant un check

### Steps to Reproduce

Go to reports any report
the consolidate or hide columns is not working if you try to uncheck

### FrappeBooks Version

0.25

### Path or Feature name

reports

### Country

US

### Language

english

### OS

Windows 11

### Additional OS Info

windows 11 2024

**Comment by akshayitzme** [comment]
@mohammadmagdyhamo 

fixed in #1060 . A new release will be published soon. Thanks for reporting the issue.
