### ISSUE TITLE
Invoice dont submitted when you have some item with 0% tax. 

### ISSUE THREAD

**Issue by Franklin0702** [frappe/books#112]
### Edit: 

This is a problem with Frappejs. Please Close it. 

### **Problem**: 

When you submit or revert an invoice with some item with 0% tax, the invoice it doenst update status. 

### **Steps to reproduce:** 
**1. Create a tax with 0%.** 
![image](https://user-images.githubusercontent.com/19265450/74992859-aceaa680-541f-11ea-8e86-72e73697c578.png)

**2. Create an Invoice, add an item and select this tax.** 
![image](https://user-images.githubusercontent.com/19265450/74992943-e8857080-541f-11ea-8f98-568130d65325.png)

**3. Save the Invoice and submit it, then you will get the following error in console:** 
![image](https://user-images.githubusercontent.com/19265450/74993406-3f3f7a00-5421-11ea-944b-675d90fb8251.png)
![image](https://user-images.githubusercontent.com/19265450/74993427-4ebec300-5421-11ea-992a-6ac2293b472b.png)
![image](https://user-images.githubusercontent.com/19265450/74993443-5aaa8500-5421-11ea-90fa-a1b03320e8c9.png)

### **What I have done:** 
The error is cause because in applyFormula function inside document.js theres not a validation to prevent null values, look at the image below: 
![image](https://user-images.githubusercontent.com/19265450/74993492-92b1c800-5421-11ea-8757-adc7ce17a5d2.png)

**To fix this I added the next lines:** 
![image](https://user-images.githubusercontent.com/19265450/74993543-abba7900-5421-11ea-8660-c93159f837e0.png)

Greetings,

**Comment by omexlu** [comment]
Same here in AppImage

**Comment by Franklin0702** [comment]
> Same here in AppImage

Hello @omexlu Check this link, I had put the solution there: https://github.com/frappe/frappejs/pull/113

Let me know if this helps you.

**Comment by omexlu** [comment]
Hello @Fatman452 yes but in appimage I can not edit something? Is the problem there fixed?

**Comment by Franklin0702** [comment]
> Hello @Fatman452 yes but in appimage I can not edit something? Is the problem there fixed?

Sorry for the delay, this quarantine have me idle.

I think this fix should work for everything cause is 'central' code. 

Best Regards and please let me know if it works,

**Comment by 18alantom** [comment]
Closing as it's been fixed in #220 and [frappejs/pull/149](https://github.com/frappe/frappejs/pull/149).
