### ISSUE TITLE
fromFormat requires an input string and a format & Setup Wizard null already exists

### ISSUE THREAD

**Issue by exandeer** [frappe/books#114]
Hello,
I cannot install v0.0.3-beta.9
I got few errors like fromFormat requires an input string and a format & Setup Wizard null already exists
![error](https://user-images.githubusercontent.com/6023081/77563392-cd60c180-6ef3-11ea-8f53-32588afddfc3.jpg)

**Comment by gramz** [comment]
Hi, same problem in v0.0.3-beta.13 , but without the errors in fromFormat

![imagen](https://user-images.githubusercontent.com/8531407/87732939-7bd29000-c78b-11ea-8afd-65ee81d80c77.png)

**Comment by davidimmanuel** [comment]
![image](https://user-images.githubusercontent.com/66516705/88758571-f8556d80-d192-11ea-9e9e-7a05a2ca5a2d.png)
I also have the same issue on my Mac. Please enlighten me guys! Thank you

**Comment by gehtalles-de** [comment]
Same here. Running on MacOS Big Sur.
<img width="611" alt="Bildschirmfoto 2021-01-23 um 19 13 36" src="https://user-images.githubusercontent.com/70889776/105610295-544e2700-5daf-11eb-8613-85e3591f400f.png">

**Comment by ddlidded** [comment]
I am having the same issue. Is there a fix?

**Comment by 18alantom** [comment]
@ddlidded not yet; it should be fixed in the next release. Development on this project has recently been restarted.

**Comment by 18alantom** [comment]
fixed in #239
