### ISSUE TITLE
[Feature Request]: Inventory Management

### ISSUE THREAD

**Issue by mujeerhashmi** [frappe/books#115]
A basic inventory management is very much required for this to be complete standalone software for a small business instead of complete ERP.

**Comment by f-9t9it** [comment]
Yes a basic inventory management would be great with it.

**Comment by jayendra13** [comment]
yes, this is indeed a very useful feature, I can contribute to add it if someone points me to that. Is there any quick and dirty way to import the code/module from https://github.com/frappe/erpnext ?

**Comment by Muzzy73** [comment]
Without batch or serial the inventory module will be incomplete. Please have it in your roadmap.

**Comment by rmehta** [comment]
Start with basic inventory management

- [x] Location master / tree
- [x] Stock Movement - to move stock to and from a location.
- [x] Stock in hand report - items (number / value) at a location (filter by location, item, date (as on date))
- [x] Inventory ledger report - item movement across locations (filter by location, item, date range)

**Comment by 18alantom** [comment]
https://github.com/frappe/books/pull/474
