### ISSUE TITLE
GSTIN to be replaced as Tax ID

### ISSUE THREAD

**Issue by Muzzy73** [frappe/books#120]
Its better to call it Tax ID as not all countries follow it as GSTIN which is more India specific.

**Comment by vonneudeck** [comment]
Also please be aware that in some countries companies have more than one Tax ID, e.g. in the European Union one can have a national and an EU tax ID.

**Comment by 18alantom** [comment]
Partial update, https://github.com/frappe/books/pull/266 causes GSTIN to be Tax ID when country is not India.

**Comment by 18alantom** [comment]
Closing this, if more changes are required over the above change then please open a new PR.
