### ISSUE TITLE
Sales invoice doesn't save, and the quantity field always resets to one

### ISSUE THREAD

**Issue by muchai** [frappe/books#121]
![image](https://user-images.githubusercontent.com/1822868/80797352-4e257400-8baa-11ea-99db-8619470a483e.png)

**Comment by muchai** [comment]
The Purchase invoice(Bill) saves, but has the same problem on the quantity field. I.e resets to 1

**Comment by rmehta** [comment]
Should be fixed in the latest beta.

**Comment by netchampfaris** [comment]
Fixed in https://github.com/frappe/books/releases/tag/v0.0.3-beta.12
