### ISSUE TITLE
import purchase invoice from PDF file

### ISSUE THREAD

**Issue by mipmip** [frappe/books#124]
I would be nice to be able to import a PDF which creates a new bill. It might be able to guess customer and total price. 

Also nice to be able to attache files to bills.

**Comment by jonathan-s** [comment]
+1 as well as be able to export said file at some later point if need be. An export would be of all files in a given date range.

**Comment by test2a** [comment]
Importing would need OCR. I guess Thats out of scope of this project, unless the guys use tesseract here

**Comment by mipmip** [comment]
Only attaching would be nice for a paperless office. OCR would be great. I would not underestimate the scope of this project.

**Comment by 18alantom** [comment]
@mipmip OCR is not the issue, supporting the myriad of possible layouts of the pdf is the problem. Once the layout is locked down it's doable.

Will look into this:
> Also nice to be able to attache files to bills.
