### ISSUE TITLE
Calendar moves up and down when trying to switch months

### ISSUE THREAD

**Issue by nh2** [frappe/books#125]
In the setup dialogue, the month switcher buttons `<` and `>` cannot be clicked repeatedly, because the number of days change per month, so the number of week rows in the calender varies, to the calender height goes up and down depending on the month.

This means you have to re-position the mouse cursor after clicking `>` each time, otherwise you accidentally click the background and the calendar disappears.

The standard solution here is to make the calendear fixed-height.

**Comment by MartinFulgueiras** [comment]
Also, when expanding the setup dialogue to full screen it is not possible to select a date in Fiscal Year End Date. Had to close, reopen and leave the setup dialogue box at the size presented initially.

**Comment by milanissimo** [comment]
Also problem with the date, it always returns one date earlier. Selecting 1st Jan 2020 will return 31st Dec 2019. Selecting 31st Dec 2020 will return 30th Dec 2020.

**Comment by 18alantom** [comment]
Fixed in this [commit](https://github.com/frappe/books/commit/7ebbddd30795196a7bb63b1aecb9bebf40c2ad6e).
