### ISSUE TITLE
Invoices: Submit button disappears

### ISSUE THREAD

**Issue by nh2** [frappe/books#128]
After clicking **Save** on an invoice, the button turns into **Submit**:

![image](https://user-images.githubusercontent.com/399535/81249854-f9f21800-901f-11ea-811e-c5e576698e6f.png)

If you then click the **Line** cell of one of the liine item rows and change it, the **Submit** button disappears:

![image](https://user-images.githubusercontent.com/399535/81249997-39b8ff80-9020-11ea-9335-d64d605faa33.png)

**Comment by rmehta** [comment]
It should probably show a "Submitted" state, since there are no further actions.

**Comment by nh2** [comment]
>  [<img alt="@ankitsinghaniyaz" width="20" height="20" src="https://avatars.githubusercontent.com/u/11331989?s=60&amp;v=4">](/ankitsinghaniyaz) [ankitsinghaniyaz](/ankitsinghaniyaz) closed this [1 hour ago](#event-5182197281)

@ankitsinghaniyaz I see the issue was closed; it would be nice to also post if/how it was fixed.

**Comment by ankitsinghaniyaz** [comment]
@nh2 on the latest version of the application these issues are resolved. Can you provide more details like what version are you currently on?

**Comment by nh2** [comment]
> @nh2 on the latest version of the application these issues are resolved.

@ankitsinghaniyaz That is great. It would be very useful if you posted that info though along with closing, because if you simply close the issue without an accompanying comment, it is unclear whether it's fixed on a current version / which one (or in which commit) it was fixed on, or whether the bug report is considered invalid.

Thanks!

**Comment by ankitsinghaniyaz** [comment]
Point taken!
