### ISSUE TITLE
Delete Ledger entries

### ISSUE THREAD

**Issue by nh2** [frappe/books#129]
I created a couple of test invoices and deleted them afterwards.

However, they still appear on the ledger after deletion:

![image](https://user-images.githubusercontent.com/399535/81250385-2195b000-9021-11ea-84f4-7f0459d0e072.png)

It is unclear in the UI how to delete them.

**Comment by rmehta** [comment]
As a general principle, we have kept ledgers as an immutable log, but makes sense to hide them out if the invoice is reverted.

**Comment by ankitsinghaniyaz** [comment]
This is in master with #222 and should be there in the next release.
