### ISSUE TITLE
Adding a customer fails with "Customer X is linked with existing records"

### ISSUE THREAD

**Issue by wichert** [frappe/books#130]
Adding a customer always fails for me:

<img width="929" alt="image" src="https://user-images.githubusercontent.com/199657/81259305-f5d1f480-9037-11ea-8c3d-b10e75076a29.png">

**Comment by bynicolas** [comment]
There is no bug on this screen. The error comes from linking the **Default Account** to an actual existing account in your chart. **Debtors** is wrong here IMO.

But there is still an issue really similar to this one here when creating an **item**.  There is a relation between `incomeAccount` and `expenseAccount` that must be made in regards to `items`, the same way your customer must be related to a payment account here, but on the **Items** screen, the field for `income` and `expense` account is not showing so you cannot link your item to the correct chart account. Giving us the same error you get here.

So found the bug, but didn't find the fix. Should maybe open another ticket in regards to the **Items** issue
