### ISSUE TITLE
[design] Add empty state for empty lists

### ISSUE THREAD

**Issue by rmehta** [frappe/books#132]

**Comment by 18alantom** [comment]
Since description isn't provided I'm assuming it's to prevent screens like this:
<img width="817" alt="Screen Shot 2021-10-20 at 13 38 48" src="https://user-images.githubusercontent.com/29507195/138053736-167fb44e-cd4c-4e61-9824-d2861bcedcf2.png">
(No payments have been made, it's an empty list)
