### ISSUE TITLE
Portable Windows version

### ISSUE THREAD

**Issue by ivangretsky** [frappe/books#133]
Good day!

Is there (or could there be) a portable Windows version? So we don't have to install to evaluate while it's in beta? And to be able to store it on dropbox?

**Comment by 18alantom** [comment]
@ivangretsky as of now we don't have a portable version. We may include one in the next release. Could you elaborate on what you meant by this:
> And to be able to store it on dropbox?

Are you talking about the portable image of the app itself?

**Comment by ivangretsky** [comment]
Yes. I do have a collection of portable apps I store on a cloud disk and run from whichever PC I am on. 
But it would be ok just to share data, I guess.

**Comment by 18alantom** [comment]
updated build in #252 portable version should be present in the next release
