### ISSUE TITLE
No choice of drive for installation - Win10

### ISSUE THREAD

**Issue by monoverde** [frappe/books#136]
The program installed to my C: drive without prompting. More people have a tiny SSD C: drive and a much bigger D: drive (HDD) where they like to keep things.

I had also remapped %appdata% to D: and the program was using C:

**Comment by doughnet** [comment]
Check this out for moving the install but keeping a symbolic link on the C: pointing to the moved location

[http://www.traynier.com/software/steammover](http://www.traynier.com/software/steammover)

**Comment by monoverde** [comment]
Thanks for pointing me towards SteamMover has been handy for a few pesky programs now.

**Comment by 18alantom** [comment]
updated build in #252 installer will now as for location; change will be present in the next release

**Comment by monoverde** [comment]
Cool! Thanks for the update.
