### ISSUE TITLE
Always showing "saving"-MacOS 0.0.3-beta.11.76

### ISSUE THREAD

**Issue by clipsess** [frappe/books#137]
When make payment for an invoice, after click "save", it keep showing "Saving"
<img width="500" alt="Screen Shot 2020-05-10 at 00 29 43" src="https://user-images.githubusercontent.com/1425765/81479467-e6c88d80-9255-11ea-94ba-d2fdc04c2e4d.png">

**Comment by 18alantom** [comment]
Not reproducible on `master` should be fixed on release.
