### ISSUE TITLE
Invoice's status is always "Draft"-Mac 0.0.3-beta.11.76

### ISSUE THREAD

**Issue by clipsess** [frappe/books#138]
After submit the invoice, in the invoice list, the status of all invoices are all "draft".

**Comment by patel1008b** [comment]
Yes, I have also experience on my mac too.

even also it does not generate a journal entry as well as a submitted invoice.

**Comment by patel1008b** [comment]
@netchampfaris

**Comment by rmehta** [comment]
This is fixed in beta-12
