### ISSUE TITLE
Settings needs to choose language

### ISSUE THREAD

**Issue by mding5692** [frappe/books#140]
**version number: v0.0.3-beta.11 on MacOS**

Put country as Canada, believe its guessing what language I'm using because shows either French and English at different times, maybe needs a language selection on settings to help

See below, side navigation bar is in English while actual section is in French:

![Screen Shot 2020-05-09 at 6 50 15 PM](https://user-images.githubusercontent.com/9067177/81486884-13fd4780-9226-11ea-801b-c655cc58adaf.png)

**Comment by 18alantom** [comment]
Closing cause almost duplicate #149 (yes I know this came earlier but that has more activity on it)
