### ISSUE TITLE
multiple tax rates in invoices should show as separate line items

### ISSUE THREAD

**Issue by test2a** [frappe/books#141]
https://i.imgur.com/RlNEMKN.png

attached screenshot where i set one item as 18% and another as 28%. the software seems to calculate proper tax but only shows the tax classification of the first item and adds taxes of all there. it should be shown separately.
add: minor typo, in case of "sales", it shows "make payment". it should read "receive payment"
https://i.imgur.com/Qza1V9C.png

**Comment by test2a** [comment]
second, is the team working on indian taxation because i am seeing issues. would it be okay to list them out separately or at once or the team wants to work on bigger issues right now?

**Comment by 18alantom** [comment]
@test2a we have recently restarted development on Books. If you are still interested you can list out the issues with Indian taxation on a _New Issue_.

**Comment by 18alantom** [comment]
Will add per-item tax breakdown when invoice item row expansion is added, for now incorrect display of rates has been removed.
