### ISSUE TITLE
[Feature Request] AUR build recipe

### ISSUE THREAD

**Issue by MrGKanev** [frappe/books#142]
I'm sure Arch/Manjaro and etc users will love your software, but now there isn't a recipe to install it. A big portion of new users don't know how to install/build software out of the "store" so creating a recipe will be a great "feature".

**Comment by ananthb** [comment]
They provide appimage builds. Just download and run them. No install necessary.

**Comment by ankitsinghaniyaz** [comment]
@MrGKanev Yes we have appimage and snap builds. We are also planning to expand to Faltpaks. I'm closing this issue for now but let's chat if you want to discuss anything.
