### ISSUE TITLE
the screen is empty for ever. mac beta.13

### ISSUE THREAD

**Issue by clipsess** [frappe/books#146]
after a long time to left it there, the screen is gray forever.
no matter what you did, force quit, reinstall, clean and install, it is gray and empty.

**Comment by clipsess** [comment]
'''
main.js:63 Error: SQLITE_CANTOPEN: unable to open database file
    at I.V [as _captureStackTrace] (bluebird.js:1109)
    at I._resolveFromExecutor (bluebird.js:3334)
    at new I (bluebird.js:2922)
    at m.acquireRawConnection (index.js:66)
    at create (client.js:290) 
'''

**Comment by clipsess** [comment]
the data file path has been changed. should check the file existence first

**Comment by ceramicheights** [comment]
I'm having the same issue because I moved things around.  Where did you put the database file so Frappe can find it?
