### ISSUE TITLE
 Language issues

### ISSUE THREAD

**Issue by molivramento** [frappe/books#149]
I chose Brazil in the initial configuration, but it remains in English.
I can't find an option to change the language.
If you don't have a translation into Portuguese, I would like to help translate, just tell me what I have to do.

**Comment by mingui** [comment]
I can also collaborate for translations in Spanish, please if you can tell us how we could collaborate. I am from paraguay

**Comment by francopan** [comment]
Yeah, also looking for a translation. Although I can communicate in english, I was looking for a software for someone who can't.
Will be glad to translate to portuguese if possible.

**Comment by 18alantom** [comment]
Related to #140. Language isn't built in yet, needs to be added.

**Comment by Helkyd** [comment]
Hi,
I have made some changes for Angola and included Translations from EN to PT....
goto https://github.com/Helkyd/books/tree/develop/src

**Comment by pgy866** [comment]
It seems that there is no PR for the international localization of UI interface?

**Comment by nilsbentlage** [comment]
I could add German translations if you like.

**Comment by 18alantom** [comment]
Thanks! I'll push something to allow translation soon (< 2 weeks) and ping here.

I've bumped this issue's priority. As of now, there's no place for one to put the translation files.

**Comment by Helkyd** [comment]
On mine i added the pt.csv under Fixtures/Verified and on electron-builder
the below to be copied when doing the installation
extraResources:
from: "fixtures/verified/pt.csv"
to: "pt.csv"

Of course you still have to load the CSV with the translations when
starting the App.

HJ

**Comment by 18alantom** [comment]
That seems like a nice solution. 

The issue I see with it is: with every translation file the installation binary increases in size. What I was thinking is to fetch the `language.csv` when setting up an instance into the resources folder. Although the downside of this is internet dependence.

Depending on the size of a single `language.csv`, I may go with your idea, thanks :)

**Comment by 18alantom** [comment]
Hey everyone, translation support has been set up.

I've added a few languages (Portuguese, French, German), but since I don't know them, I can't vouch for their accuracy.

In case anyone would like to contribute I have written a few notes here: https://github.com/frappe/books/wiki/Contributing-Translations

Thanks ✌️

**Comment by nilsbentlage** [comment]
Hey @18alantom - Thx very much for the new feature. I'm testing it right now. I noticed there's a little error in your wiki, saying we can call
`yarn scripts:translate -l [region code]` to create a new csv-file, but it's `script:translate` instead. 
Greetings!

**Comment by 18alantom** [comment]
Thanks! I've fixed it.

**Comment by uc77** [comment]
Guys how am I able to switch languages in Frappe Books? I can see this issue is closed but do not see any built in solution?
