### ISSUE TITLE
[feature request] Quotations/estimates

### ISSUE THREAD

**Issue by judbd** [frappe/books#151]
Hello, frappe books seems great!

there's just one thing missing so I can use it: quotation/estimate. It works the same way as invoices, but with independent numbering and an "approved" and "send invoice" button. When a quote is approved, it appears in the pipe, and when it is invoiced, an invoice is automatically created.
This would be perfect for small businesses because it would cover all the basic needs.

Maybe this feature already exists in ERPnext.

Thank you!

**Comment by ffarkas** [comment]
You're right. It's exactly the feature I miss. It would be great if it could be implemented.

**Comment by nkadondo** [comment]
Sure! that is one part of the puzzle which is missing. Looking forward to the quotation feature

**Comment by Tabarane** [comment]
hi , has this feature been implemented? this is the only missing thing from a full app :))

**Comment by 18alantom** [comment]
@Tabarane not yet, this issue will be closed once it has been added in.

**Comment by akshayitzme** [comment]
Closing as completed.
