### ISSUE TITLE
Unable to scroll journal entry rows

### ISSUE THREAD

**Issue by bhsrmn** [frappe/books#155]
In the journal entry screen, I am unable to scroll down to add new rows. 

In my screen, I can only add 10 rows.
![Issue](https://user-images.githubusercontent.com/62752551/86465520-68690300-bd4f-11ea-9856-623b17bf82c1.png)

When I remove overflow on the app element, I am able to scroll and add more rows.
![Issue fixed](https://user-images.githubusercontent.com/62752551/86465733-dc0b1000-bd4f-11ea-964f-f49884d2b14a.png)

**Comment by 18alantom** [comment]
Closing as it's fixed in PR #220
