### ISSUE TITLE
Export Reports to PDF (print), .xls, maybe other formats

### ISSUE THREAD

**Issue by davi5e** [frappe/books#157]
If I need to share the reports, how could I export them to PDF, or at least print them?

As of this moment, I'd need to copy the entries to a spreadsheet (manually) to achieve this. This is also another problem, since there is no way to export the reports to `.xls` or other formats.

**Comment by tshrinivasan** [comment]
Thanks for the good software.

Importing/Exporting various formats of all the data is very essential operation.

I started using frappe books for day.
Found there is no export,import feature.
Stopped adding data to it, as it will lead to duplicate works.

Will use frappe books, after it gives import/export feature.

**Comment by 18alantom** [comment]
Added it as a card: https://github.com/frappe/books/projects/1#card-75802030
