### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by rmehta** [frappe/books#16]
- [x] Address
- [x] Contact
- [x] Accounts
  - [x] Payment
  - [x] Bill
  - [x] Journal Entry https://github.com/frappe/accounting/pull/26
- [x] Sales
  - [x] Quotation
  - [x] Sales Order
  - [x] Order Fulfillment
- [x] Purchase
  - [x] Purchase Order
  - [x] Purchase Receipt

**Comment by revant** [comment]
https://github.com/frappe/accounting/commit/0e9edf2d3b71b3a971ac31e0e1a21e7d6f0717a8

added Payment and Invoice. (Bill?)

**Comment by netchampfaris** [comment]
https://github.com/frappe/accounting/commit/9fed2fbb198fdb26d0f47f2bdf946d277895555c
