### ISSUE TITLE
FrappeBooks installation failed - SetupWizard null already exists (Windows 8.1)

### ISSUE THREAD

**Issue by milanissimo** [frappe/books#160]
I just downloaded and trying to install Frappe Books on my Windows 8.1 laptop (latest Chrome). I got error upon clicking Next button after filling up company, name, country, fiscal year (the calendar selection has another issue of its own). Error message: SetupWizard null already exists. Then stopping, I can't continue with the installation. Deleting .db file and redo the setup didn't work either.

![image](https://user-images.githubusercontent.com/5997569/87750664-429b2e00-c826-11ea-81ab-22439be4a558.png)

**Comment by 18alantom** [comment]
Closing as this is a duplicate of #114.

**Comment by 18alantom** [comment]
Closing as this is a duplicate of #114.
