### ISSUE TITLE
Cannot select a file to load the company transactions

### ISSUE THREAD

**Issue by aakvatech** [frappe/books#164]
![image](https://user-images.githubusercontent.com/35020381/90174389-927dfe00-ddae-11ea-9ef0-9792d057c559.png)
None of the items on this screen is clickable.

Stuck at this point.

**Comment by aakvatech** [comment]
https://github.com/frappe/books/blob/master/src/pages/DatabaseSelector.vue

This file seems to be the problem. If I rename frappe-books.db to something like mycomp.frappe-books.db, then after reopening Frappe Books, it prompts to open existing file.

**Comment by OrbitalT** [comment]
I'm having this problem as well, your unable to click or change the db file and i was forced to uninstall the app to get the fix.

**Comment by Dariusz1989** [comment]
Same bug > https://github.com/frappe/books/issues/223

**Comment by 18alantom** [comment]
Fixed in https://github.com/frappe/books/pull/237 (90% sure), will reopen/recreate if reoccurs.
