### ISSUE TITLE
Dummy/Example Data

### ISSUE THREAD

**Issue by doughnet** [frappe/books#165]
Be nice to have a dummy/example data (like QB Desktop does) to get a feel for how the experience is with data filled in already.  Could be as easy as downloading a SQL .db file?

**Comment by laptopmutia** [comment]
anyone willing to share their .db files? for educational purposes of course

**Comment by 18alantom** [comment]
Sure, here you go: https://drive.google.com/file/d/1l3lInnFkDTQYPk7GtmS7C7d4sP3emkKS/view?usp=sharing

**Comment by 18alantom** [comment]
done here: https://github.com/frappe/books/pull/381
