### ISSUE TITLE
Datepicker is not accurate

### ISSUE THREAD

**Issue by himynameistimli** [frappe/books#166]
Might be using it wrong, but when I select Jan 1, 2020 as the start of my FY, its selects Dec 31 2019 as the start. In this photo, I had to select Jan 2 in order for the field to show Jan 1

![image](https://user-images.githubusercontent.com/6541272/90466008-3cf57880-e143-11ea-9ad7-75633e7b65bc.png)

**Comment by 18alantom** [comment]
Closing as it's been fixed in PR #220
