### ISSUE TITLE
How we can have multiple bank accounts?

### ISSUE THREAD

**Issue by shantiwebsolution** [frappe/books#169]
Here there is only one bank accounts possible.
If we have 2 bank account for same business then from where we can add ?

**Comment by bynicolas** [comment]
You simply need to add a new account under `Setup > Chart of Accounts > Assets` (find the right section to add it under) and set the `Account type` as `Bank` or `Cash`. Make sure `Is Group` is **NOT** checked

**Comment by shantiwebsolution** [comment]
Perfect
