### ISSUE TITLE
Profit and Loss report erroneous

### ISSUE THREAD

**Issue by bynicolas** [frappe/books#176]
The **Profit and Loss** report is erroneous when you select the `Yearly` view.

it seems to be an issue with the date range that don't match the expected fiscal year dates set in the *Settings*.

For instance, I expect to get totals for each accounts in the range `2020-01-01` to `2020-12-31`, but some values are missing from the total because the reports thinks its in an other fiscal year.

Anything before 2020-04-01 is considered 2019
Anything up to 2021-03-31 is considered 2020
And neither match the expected fiscal year dates

![image](https://user-images.githubusercontent.com/10983565/94771280-e2c41600-0384-11eb-9547-c117a02ac768.png)
![image](https://user-images.githubusercontent.com/10983565/94771251-d3dd6380-0384-11eb-8d92-b1af6e8c6d73.png)

**Comment by 18alantom** [comment]
Seems to be caused by the _date off by one day bug_, this may have been fixed in #220. Not closing cause it needs further evaluation.

**Comment by 18alantom** [comment]
Fixed in #305

**Comment by bynicolas** [comment]
Is this really fixed? I see the same behaviour in v0.4.2-beta.0.

A yearly P/L report from `2021-01-01` to `2021-12-31` would give a report range from `2020-2021`

A half yearly report for the same date range would give from `Oct 2020 - Mar 2021` and `Apr 2021 - Sep 2021`

Monthly and Quarterly P/L reports seems to fit the requested range

**Comment by 18alantom** [comment]
Will close this when it's fixed and tests have been added to verify it.

**Comment by 18alantom** [comment]
<img width="1004" alt="Screen Shot 2022-05-27 at 01 13 04" src="https://user-images.githubusercontent.com/29507195/170565078-673a59b1-589e-4d05-b8e9-e67220b11a05.png">

All reports have been rewritten, PnL report now shows the **Until Date** of the interval (monthly, quarterly, etc), will add a description tooltip soon to make things clearer.
