### ISSUE TITLE
Opening Frappe and just showing a grey screen

### ISSUE THREAD

**Issue by georgekrousti** [frappe/books#177]
Every time I open it, it is just showing a grey screen. 

I have re-installed the software from scratch but have the same problem.

I deleted the file that had my account details and it started to happen after that.

This is the error that is showing up:

main.js:63 Error: SQLITE_CANTOPEN: unable to open database file
    at I.V [as _captureStackTrace] (bluebird.js:1109)
    at I._resolveFromExecutor (bluebird.js:3334)
    at new I (bluebird.js:2922)
    at m.acquireRawConnection (index.js:66)
    at create (client.js:290) a "mounted hook (Promise/async)"
g.default.config.errorHandler @ main.js:63 

Not sure what to do. Thanks.

**Comment by wvfrm** [comment]
i am having the same issue , due to some mis hap i deleted the db file and now the application won't open , any idea/tips on how to resolve this issue . 

thanks.

**Comment by dlandes77** [comment]
#I have the same issue. Just a blank, grey screen after installation... any pointers how to get the app working? I tried this with a bunch of versions, not only the latest build. Am I missing some prerequisite software on my mac maybe?

**Comment by 18alantom** [comment]
@georgekkkkruz, @dlandes77 the issue was `electron` related. Build-related fixes were made in #216 can you retry setting it up now, it should work as expected.
