### ISSUE TITLE
Value missing for "Payment For" - Field not available

### ISSUE THREAD

**Issue by bsukhadia** [frappe/books#178]
**"Payment For"** field seems missing for payments UI. Therefore unable to post the payment transactions.

Also, ran into [Datepicker issue](https://github.com/frappe/books/issues/166) so it is worth bumping up the priority for issue #166.

`0.0.3-beta.13 (0.0.3-beta.13.92)`
`macOS Catalina`

Attached screenshot for reference.

![image](https://user-images.githubusercontent.com/17866455/96553290-93fa0400-12d2-11eb-80ab-ff4199e33eaf.png)

**Comment by 18alantom** [comment]
@bsukhadia the _Payment For_ field refers to the Reference table at the bottom. The table needs to have at least a single row to make a _Payment_ transaction.

Thanks for bringing this up. The error message should be reworded.

**Comment by 18alantom** [comment]
fixed in #236
