### ISSUE TITLE
Unable to Scroll

### ISSUE THREAD

**Issue by gegobyte** [frappe/books#182]
I just installed Frappe Books, on many sections, the pages are not scrolling. The Dashboard page is not scrolling, Sales > Invoice page is also not scrolling. If I click on Print on Invoice, the resultant print page is scrollable. All sections under Reports are scrollable.

The version I am running is v0.0.3-beta.9

**Comment by AzharBhyat** [comment]
Have the same issue

**Comment by 18alantom** [comment]
Fixed in #220, should be out in the next release.
