### ISSUE TITLE
Multi-currency accounts

### ISSUE THREAD

**Issue by dedunumax** [frappe/books#183]
Hello! I love the product please keep doing awesome stuff!

But I noticed I cannot create accounts with different currencies. ERPnext has this feature. It would be great if you can add it here.

Thanks in advance.

**Comment by Dariusz1989** [comment]
+1 to me too. Currnetly dealing with GBD/USD/EUR and more! :c

**Comment by njmulsqb** [comment]
+1 

I have balance in USD as well while PKR is the default currency, it would be great if I can add USD account and it gets shown in PKR with latest exchange rate.

**Comment by digitalentity** [comment]
+1 for this feature. Dealing with CHF accounts and payments in EUR. Can have a separate account for EUR in my bank, but that would make accounting in Frappe hard...

**Comment by akshayitzme** [comment]
closing this cause of #816
