### ISSUE TITLE
Project Progress?

### ISSUE THREAD

**Issue by philippnagel** [frappe/books#192]
Hello,

To me it seems like the project might be dead. 

At least pull requests do not seem to be accepted anymore. Last commit was in 2020.

Would love to hear from the maintainers!

Cheers

**Comment by Xanaxiel** [comment]
My sentiments exactly. I think they're working on a redesign/rebrand into [erpnext](https://github.com/frappe/erpnext), specifically for [this module](https://erpnext.com/open-source-accounting). 

What I found weird is that the latest release was [beta.13](https://github.com/frappe/books/releases/tag/v0.0.3-beta.13) yet the Frappebooks [download page](https://frappebooks.com/download) references beta.9 so not sure if it might be dead or it's currently a WIP undergoing a redesign/rebrand

**Comment by philippnagel** [comment]
That would be a shame as I think the big differentiating feature of Frappe Books is that it does not rely on a hosted service.

The alternatives like e.g. GNUCash are way behind in terms of UX and focus of the feature set.

Would be great if the maintainers would comment.

**Comment by 18alantom** [comment]
@philippnagel progress had been stalled for a while, but we are now dusting off and restarting it. Thanks for asking :)
