### ISSUE TITLE
General Ledger repeated values

### ISSUE THREAD

**Issue by Yazansammour** [frappe/books#199]
I am not sure if this is a bug or it supposed to look like this, but why the invoice appeared two times in the ledger, the total is double the value of the invoice.

<img width="973" alt="Screen Shot 2021-05-13 at 12 13 55 AM" src="https://user-images.githubusercontent.com/12206030/118038577-5a790b00-b380-11eb-87eb-5bf05c1a745e.png">

**Comment by saileshkush95** [comment]
I'm also facing same problem, did you find any way to resolve this issue

**Comment by 18alantom** [comment]
Fixed on `master`, should be out on release.
