### ISSUE TITLE
Sales invoice is not calculating total and not generating invoice

### ISSUE THREAD

**Issue by magicrocks** [frappe/books#203]
![frappe book Invoice Issue](https://user-images.githubusercontent.com/29063807/121220551-50282f00-c8a2-11eb-91e2-3aec010c6f9f.JPG)

I am trying to create invoice but when I am adding an item in the invoice, the subtotal and total is not calculating. System is not allowing us to save as a draft.

**Comment by 18alantom** [comment]
Not replicable on `master`, may have been fixed in #220
