### ISSUE TITLE
Publish as flatpak

### ISSUE THREAD

**Issue by lallenfrancisl** [frappe/books#206]
Can you publish the app as flatpak for linux users ? It makes it a lot easier to update than appimage.

**Comment by ankush** [comment]
Also, PPA / default repositories will help (for Debian-based distros) Since this has no system dependencies right now maintaining it won't be much pain. 


I can work on this _someday in the future_ if you want @18alantom

**Comment by JeanGrenouille010101** [comment]
This would be great especially now as things like flathub are becoming standard on most distros

**Comment by kskarthik** [comment]
I was able to build the flatpak successfully. Will try to publish on the flathub soon

**Comment by kskarthik** [comment]
@18alantom @akshayitzme i have a few queries:

1. Does the app need network access?
2.  Does it access any other dir on user's home apart from `~/Frappe Books` ?

In flatpak, i have tested the app is working fine with networking off & confining the access to the above dir

**Comment by kskarthik** [comment]
The flatpak is published! :partying_face: https://flathub.org/apps/io.frappe.books

Code: https://github.com/flathub/io.frappe.books

**Comment by kskarthik** [comment]
this issue can be closed
