### ISSUE TITLE
Tax rate and Item rate doesn't gates updated automatically on updating the Item in Sales and Purchase invoice.

### ISSUE THREAD

**Issue by piyushsinghania** [frappe/books#215]
Steps to reproduce the bug:-
1) Create two items with different names and tax rates (say GST-18% and GST-0%)
2) Create a sales invoice add a customer fill in other details
3) Add your item 1, let's say an item with GST-0%
4) Add the desired quantity and rate
5) A grand total will be appearing by that time.
6) Now change the item and select the other one ( say with GST - 18%)
7) Now you can see that the Tax rate doesn't gates updated automatically
8) Also you can even submit the invoice in such a scenario, making the tax calculations to be wrong.
9) This causes an item created with GST - 18% to be passed with GST - 0%

**Comment by ankitsinghaniyaz** [comment]
This is solved and should be out in the latest build
