### ISSUE TITLE
Sales invoice payments should be termed as received 

### ISSUE THREAD

**Issue by piyushsinghania** [frappe/books#218]
@ankitsinghaniyaz Currently the sales invoices on making payment show the status as paid, it can be enhanced if we show the status as received. This will enhance the readability of the software.

**Comment by 18alantom** [comment]
@piyushsinghania using ERPNext Accounts as a compass, _Paid_ as a status seems fine.

Consider it this way, the status just tries to indicate whether the invoice has been paid for or not, direction of payment is irrelevant here.
