### ISSUE TITLE
Can not load file/database! 

### ISSUE THREAD

**Issue by Dariusz1989** [frappe/books#223]
Hey

Just started using it, I somehow managed to "log off" and I Can not specify my database file again :- (

![image](https://user-images.githubusercontent.com/13185728/138615223-f33bb1ca-a59d-4eaa-829a-6c28752ed639.png)

What do I do on this screen? 
Clicking on select file does not do anything...

**Comment by 18alantom** [comment]
Closing as it's a duplicate of #164
