### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Dariusz1989** [frappe/books#224]
Hello
Please... my eyes are burning. Dark mode ?

**Comment by TomSaw** [comment]
As workaround for long sessions, you can overwrite the main containers `background-color` in developer tools (Menu->View->Developer Tools)

However, this overwrite is lost on quit but takes a trained 'hacker' just 20 seconds to re-setup.

**Comment by akshayitzme** [comment]
Feature added in #873
