### ISSUE TITLE
Description/comment in Invoice section + more

### ISSUE THREAD

**Issue by Dariusz1989** [frappe/books#225]
Hey
Is it possible to add a description to each item that I can customize per invoice?
As well as an additional order number field if I wish to specify a second one on top of the generated one.
Also... if I wish to specify payment method details on the invoice at bottom/etc... 

Oh dear, there is a lot stuff missing, were more like in Alpha than beta are we :- ) 
Other than that I like the app! ^^

**Comment by 18alantom** [comment]
You can add a note in an invoice but not an individual item description.

Thank you! Yes, you are right a lot of features need to be added. We've recently restarted development on this is so we'll be adding in more features.

**Comment by 18alantom** [comment]
Same reason as https://github.com/frappe/books/issues/233
