### ISSUE TITLE
Attach bill images on the transaction.

### ISSUE THREAD

**Issue by Dariusz1989** [frappe/books#226]
Hey

Still learning, but I'm fairly sure I got it wrong if I want to record purchases of products/services/payments. 
Say buying pc/ car/etc... can I do it in this app? Can I attach an image of the receipt/etc?

**Comment by 18alantom** [comment]
Yup, you can record purchases but an image of the receipt can't be added yet. Besides the main purchase info, you can add a note that provides additional details.

**Comment by ankitsinghaniyaz** [comment]
Will the attachments be saved in the db? It can make it a bit heavy and difficult to move around.

It can be cool to have an image service integration whose API keys user can provide for storing images there and save url in db.
