### ISSUE TITLE
Description data not visible in the general ledger

### ISSUE THREAD

**Issue by piyushsinghania** [frappe/books#231]
Steps to Reproduce
1) Create an item and all details
2) Create a supplier/customer
3) Create and submit a new sales/purchase invoice respectively, to record general entries.
4) Go to the general ledger under reports section

![image](https://user-images.githubusercontent.com/69912046/139584376-5f8560d1-b15e-4fdb-9dad-f434953ece30.png)

**Comment by 18alantom** [comment]
Closing cause https://github.com/frappe/books/pull/242 renders it redundant.
