### ISSUE TITLE
Remote database connection

### ISSUE THREAD

**Issue by saileshkush95** [frappe/books#238]
Please add features for remote database connection.  I think we should add features to support multiple database. Postgresql would be great.

**Comment by 18alantom** [comment]
MySQL ORM code already exists in `frappejs` it's just been disconnected, may include this in a future release. For now we'll just be focusing on SQLite.

**Comment by saileshkush95** [comment]
> MySQL ORM code already exists in `frappejs` it's just been disconnected, may include this in a future release. For now we'll just be focusing on SQLite.

Can we easily enable this features, if, can you please point where i need to modify code

**Comment by 18alantom** [comment]
MySQL backend class: https://github.com/frappe/books/blob/master/frappe/backends/mysql.js

Closing this as no work will be done in this direction for at least until v2 (we still have to reach v1). And even in that case, most probably won't be adding just a remote DB connection.
