### ISSUE TITLE
Dependency error in local

### ISSUE THREAD

**Issue by saileshkush95** [frappe/books#263]
![Screenshot from 2021-11-29 21-30-24](https://user-images.githubusercontent.com/28560875/143898746-74df1d49-c3ee-412d-ac10-1d025fac39f9.png)

**Comment by 18alantom** [comment]
@saileshkush95 this happens when yarn doesn't update it's cache.

```bash
rm -rf node_modules
yarn cache clean —all
yarn install
yarn link frappejs
yarn electron:serve
```

(also make sure you're using the latest commit of `frappejs`)
