### ISSUE TITLE
No registered package found called "frappejs"

### ISSUE THREAD

**Issue by saileshkush95** [frappe/books#270]
![Screenshot from 2021-12-05 14-29-26](https://user-images.githubusercontent.com/28560875/144739789-01a9567f-8cb1-4754-9400-7b96323356d0.png)

**Comment by 18alantom** [comment]
@saileshkush95 you have to first clone `frappejs`, then run `yarn` and `yarn link` in that repository.

see this: [Developing with FrappeJS](https://github.com/frappe/books#developing-with-frappejs)
