### ISSUE TITLE
Didn't display any graph in dashboard.

### ISSUE THREAD

**Issue by saileshkush95** [frappe/books#272]
there is no any effect of purchase bill and sales bill in dashboard section.
![Screenshot from 2021-12-06 23-51-25](https://user-images.githubusercontent.com/28560875/144898659-f527afe1-940d-4bef-b1b2-f6bf0145235f.png)

**Comment by 18alantom** [comment]
Any steps to reproduce? It's working for me.

Does it appear on refresh? In dev mode the at times gets out of sync.

**Comment by saileshkush95** [comment]
> Any steps to reproduce? It's working for me.
> 
> Does it appear on refresh? In dev mode the at times gets out of sync.

No need to follow any step. 
Just start from scratch  and create some invoices bill or purchase bill

**Comment by zerotraceme** [comment]
Check your fiscal year settings. I had it setup for next year, so the dashboard didn't show anything for me, either. After changing that to the current year it displays my transactions and graph just fine!

Setup > Settings > General

![image](https://user-images.githubusercontent.com/47125897/146562336-351244c3-b6a9-4d32-b219-d29dde4dc1d9.png)

**Comment by saileshkush95** [comment]
Yup that's the problem
