### ISSUE TITLE
0.0.4 beta Blank Screen issue (first time running)

### ISSUE THREAD

**Issue by MountBlu** [frappe/books#273]
I just downloaded the latest release 0.0.4. Running for the first time all I see is blank/grey screen. Developer tools has this error.

```
initialization.js:72 regional model updates failed Error: SQLITE_CANTOPEN: unable to open database file
main.js:61 Error: SQLITE_CANTOPEN: unable to open database file
```

How do I create the DB for first time running?

**Comment by ankitsinghaniyaz** [comment]
@MountBlu Could you please help us with some more information to investigate this.
1. What OS are you on?
2. Did you install 0.0.3 before installing 0.0.4 or was it a clean install?

**Comment by MountBlu** [comment]
1. Win10 64bit
2. I did install 0.0.3, since it has a lot of bugs, I uninstalled it. Reinstall 0.0.4 and I have this issue.
 
Not sure if this helps, but I run `0.0.4.exe` for the first time, since it's giving me blank screen. I then run `0.0.4.setup.exe` and it's showing the same blank screen with the error above.

**Comment by MountBlu** [comment]
UPDATE:

It seems to be working now after I remove `frappe-books` folder from `AppData\Roaming`. So I guess it's a leftover from previous version.
