### ISSUE TITLE
Cannot read properties of null (reading 'map')

### ISSUE THREAD

**Issue by knightknight** [frappe/books#279]
Trying to input a cheque as payment and submit.

- Windows 10 Build 19043
- FrappeBooks v0.0.4-beta.1

![Screenshot 2021-12-16 164712](https://user-images.githubusercontent.com/5765628/146414986-cbf48372-2b0c-4f9a-a71f-551e3bfb9f7d.jpg)

**Comment by 18alantom** [comment]
@knightknight thanks for pointing this out, should be fixed in this: https://github.com/frappe/books/releases/tag/v0.0.4-beta.2 release.
