### ISSUE TITLE
Menu items jump to other menu category

### ISSUE THREAD

**Issue by zerotraceme** [frappe/books#280]
When I click on "Items", "Payments", or "Journal Entry" in menu category "Purchases", it jumps to the entry in menu category "Sales". Not sure if this is the intended behaviour or not.

Mac OS 10.13.6

![image](https://user-images.githubusercontent.com/47125897/146466290-b30dbdd5-abf6-44de-a66a-c80f5e8182cc.png)

**Comment by 18alantom** [comment]
@leprodude I was aware of this but never got around to fixing it, thanks for the push :) 

I've created a separate section for the common entries. Update's in this release: https://github.com/frappe/books/releases/tag/v0.0.4-beta.2

**Comment by zerotraceme** [comment]
Great to hear, thanks for fixing it. It works fine now!
