### ISSUE TITLE
Fix or enforce precision setting

### ISSUE THREAD

**Issue by zerotraceme** [frappe/books#284]
My current setting for precision is 2. After creating an item and setting its rate to 0.0013 it shows as 0.00 as expected (not ideal on bills though). The correct amount is there, when I click the 0.00.

When I add this item to a Bill however, the amount is 0.00 and doesn't come as 0.0013 like expected, I have to put that in manually, which then works. I'd say either fix that so it calculates correctly, or don't allow me to put in 0.0013 with precision 2 in the first place.

Use case: Billing an API on a per request basis.
Ideally, I would only want to set a higher precision for the API call item, otherwise my dashboard gets too crowded.
Showing higher precision automatically whenever there is content could be an option.
Or maybe being able to set precision on a per item basis?

Just after adding item:
![image](https://user-images.githubusercontent.com/47125897/146559128-790a81ae-f80d-4ae8-8567-e49e3402c56d.png)

Editing for the correct price:
![image](https://user-images.githubusercontent.com/47125897/146559280-67a09058-e87e-462f-a25b-74ebc9eb7b10.png)

After editing the price:
![image](https://user-images.githubusercontent.com/47125897/146559320-d98bebc1-4f75-4edd-8a8f-8c1ce3ed2ff6.png)

**Comment by 18alantom** [comment]
Yup, this is a [work in progress](https://github.com/frappe/books/projects/1#card-72604688) currently, a bit of a big change hence taking time.

The precision setting doesn't  do anything as of now. The plan is to maintain sufficiently high internal precision which will be constant so as to circumvent having to deal with precision precision change DB updates. The precision setting will then just alter the mantissa length, i.e. just display.

Will close this issue once precision setting is hooked up fixed.

**Comment by 18alantom** [comment]
Closing cause: https://github.com/frappe/books/pull/268 merged.
