### ISSUE TITLE
Export to ERPNext

### ISSUE THREAD

**Issue by imagina** [frappe/books#285]
Can the data be exported/imported in ERPNext. 

It will be great to start with Frappe Books and then move to ERPNext?

**Comment by 18alantom** [comment]
We will be adding in exports (it's in the Roadmap), targeting these formats: `.csv`, `.json` and maybe `.xls`.

This should allow for importing it into any software. A few changes may have to be made to the files before importing into  ERPNext since one would have to match the ERPNext template.

**Comment by 18alantom** [comment]
Closing this cause #290
