### ISSUE TITLE
Implement a basic POS like interface for invoice

### ISSUE THREAD

**Issue by esafwan** [frappe/books#289]
I am looking at building a POS like interface for the invoice feature. I was wondering if there is a developer channel or group where we can talk to existing developers as I try this out.

**Comment by 18alantom** [comment]
@esafwan we had a discuss earlier but it's inactive. [Github Discussions](https://github.com/frappe/books/discussions) can be used, you could start a new topic.

**Comment by esafwan** [comment]
Started a discussion [here](https://github.com/frappe/books/discussions/291). 

https://github.com/frappe/books/discussions/291
