### ISSUE TITLE
Please how do I add the available quantity of stock for each item 

### ISSUE THREAD

**Issue by Eminence231** [frappe/books#292]

**Comment by 18alantom** [comment]
@Eminence231 this feature has not yet been added.

I've included basic inventory management in the roadmap, you should get it one or two releases from now.

If you have any thoughts on what should go into it then do let us know.

**Comment by 18alantom** [comment]
Closing this as it's a question and the feature is in the roadmap. You can create a [discussion](https://github.com/frappe/books/discussions) post for this, if you'd like.
