### ISSUE TITLE
Report an Issue button

### ISSUE THREAD

**Issue by rmehta** [frappe/books#296]
Add an easy way for people to discover github issues / discussions

**Comment by ankitsinghaniyaz** [comment]
If there's an open-source/free option of something similar to this it will be very helpful
https://usersnap.com/

cc: @18alantom

**Comment by rmehta** [comment]
No 3rd party SAAS!

Just direct them to GitHub Issues?

**Comment by ankitsinghaniyaz** [comment]
yep that should be possible.
