### ISSUE TITLE
How to add onChange event for a field

### ISSUE THREAD

**Issue by Helkyd** [frappe/books#309]
Hi,
Not a bug but a doubt after searching long time...
How to have a onChange event for a field like Selection (a,b,c) when ever user selects different value and specially if on a Quickeditform or TwocolumnForm ?

Example on Transaction.js we have Make Payment and openQuickEdit.. need to check when paymentmethod changed values from CASH to BANK

Thanks in advance.

**Comment by 18alantom** [comment]
As of now, there is no functionality to fire field level `onChange` handlers. In place of this, there is a [`formulaDependsOn`](https://github.com/frappe/books/blob/master/models/doctype/PurchaseInvoice/PurchaseInvoice.js#L60) functionality.

Most probably won't be adding such an event on a field so as to prevent unnecessary side effects. (The dynamic nature of things already poses a problem in a few areas, this wouldn't help).

If you want to add something of the sort you can alter these functions to trigger the `onChange` handlers:
- [`QuickEditForm::valueChange`](https://github.com/frappe/books/blob/master/src/pages/QuickEditForm.vue#L197)
- [`TwoColumnForm::onChange`](https://github.com/frappe/books/blob/master/src/components/TwoColumnForm.vue#L158)
