### ISSUE TITLE
Cannot Initialize Database.. Error no such table SingleValue

### ISSUE THREAD

**Issue by Helkyd** [frappe/books#321]
Hi,
Don't know if is happening to all and if it does happen on a new fresh clone... but because i have made some changes but none on FrappeJS when on creating a new DB the below error is shown and does not create the new DB

asyncToGenerator.js:6 Uncaught (in promise) Error: select `fieldname`, `value`, `parent` from `SingleValue` where `fieldname` = 'internalPrecision' and `parent` = 'SystemSettings' or (`fieldname` = 'displayPrecision' and `parent` = 'SystemSettings') - SQLITE_ERROR: no such table: SingleValue
    at createQueryBuilder (make-knex.js:315)
    at SqliteDatabase.knex (make-knex.js:100)
    at _callee16$ (database.js:311)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:294)
    at Generator.next (runtime.js:119)
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
initializeMoneyMaker @ index.js:19
executePostDbConnect @ database.js:820
connect @ database.js:19
_callee3$ @ initialization.js:46
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonymous) @ runtime.js:119
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
connectToLocalDatabase @ initialization.js:36
_callee4$ @ DatabaseSelector.vue:225
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonymous) @ runtime.js:119
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
connectToDatabase @ DatabaseSelector.vue:219
_callee$ @ DatabaseSelector.vue:202
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonymous) @ runtime.js:119
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
newDatabase @ DatabaseSelector.vue:199
invokeWithErrorHandling @ vue.esm.js:1872
invoker @ vue.esm.js:2197
original._wrapper @ vue.esm.js:7609

**Comment by 18alantom** [comment]
Hey, I tried creating a new instance on a fresh clone, didn't get any errors.

I recently merged a huge PR https://github.com/frappe/books/pull/320 which removes Frappe JS as a dependency, this may have broken your changes.

Frappe JS code now lives in the books repository: https://github.com/frappe/books/tree/master/frappe

**Comment by 18alantom** [comment]
You shouldn't be facing this on the latest clone cause the _no such table error_ in `frappe.db.getSingleValues` has been handled: https://github.com/frappe/books/blob/master/frappe/backends/database.js#L323

Closing this issue for this reason.
