### ISSUE TITLE
Can't Set Address in Invoice Settings

### ISSUE THREAD

**Issue by nilsbentlage** [frappe/books#333]
<h2>Description</h2>
I pulled the master Branch, made some adjustments and built it with yarn. Everything is working fine but i cant set the address in the invoice settings. When i hit save it just disappears and is never seen again. Console doesn't throw any errors.
Maybe you have any ideas? 

edit: The error is also appearing in the address-input-component in the customer-settings

**Comment by 18alantom** [comment]
Was able to replicate it in the Customers > Address, will push a fix soon.

**Comment by 18alantom** [comment]
Fixed: https://github.com/frappe/books/commit/2e1b8bfa132d545bc11008684d143b7b115ef481

**Comment by nilsbentlage** [comment]
Thx so much! Works for me. I took a look by myself before but didn't get it. Maybe you are interested in a Feature, which allows users to enter net prices and get tax calculated backwards. I'm implementing that for a friend. We could enhance that with a checkbox on the corresponding tax, maybe.

**Comment by 18alantom** [comment]
You're welcome!

That seems like a useful feature. I'm open to adding it in, but it make take a while.

I want to enable other invoice level settings too, such as multi-currency invoices, so will probably try and build some common UI for these settings.

> We could enhance that with a checkbox on the corresponding tax

Could you give me some more points on how you imagine this feature to be? Will this setting be on a per-row basis or for the whole invoice?

**Comment by nilsbentlage** [comment]
Hello again,

I implemented that feature as a Hack right now and did it on a per-row-basis, so my friend has the ability to mix and match both ways of calculating the tax as he needs it (one for used parts, one for new Parts). 

It also saved me some trouble when the checks at the end of the invoice compared the values (with "debit" i think?). So i undid my first try, where i implemented that on the sum-functions for the invoice footer. 

I think it's ok to anchor that feature to a created "tax"-element. So maybe a Switch (Checkbox) when creating a tax, with a title like: 
Defined prices are  "net | gross"
could do the trick.

I could try to implement that for you and give you a PR, but the Project is quite large and Vue new for me, so maybe i dont get the best practice at first hit ;)

**Comment by 18alantom** [comment]
Per row is fine too, we could also add a global setting that sets it for all the rows. But I feel since this is an invoice level calculation, the setting should be on the invoice itself.

I was thinking of adding row expansion for the invoices to show additional information such as item-wise tax breakdown, item details, etc.

This seems like an apt place for the checkbox, the global setting can be placed in a side pane perhaps, as there may be other invoice level customizations.

> I could try to implement that for you and give you a PR

That would be amazing!

>but the Project is quite large and Vue new for me, so maybe i dont get the best practice at first hit ;)

That's alright, three months ago I knew no Vue :)
If you do give it a shot, let me know if you need any help.
