### ISSUE TITLE
Software requirements specification document

### ISSUE THREAD

**Issue by KiziridisK** [frappe/books#335]
Hello,

my name is Konstantinos Kiziridis. I am studying Computer Science at Aristoteleio University in Greece (Thessaloniki). 
As an assignment for one of my cources i had to create a SRS  Document for one open source project. I picked your project 
as it seams interesting and a good opportunity to study for my course. I am currently writing it in my mother language (Greek), 
but after i finish it i intend to translate it in english as well. If you are interested in reading my paper please let me know and i will
upload it when it's ready. Thanks!

**Comment by 18alantom** [comment]
Hey @KiziridisK, yup we're interested in reading your paper! :)

Feel free to open another Issue (or comment on this) when you're done with it, closing this for now.
