### ISSUE TITLE
Vat comply url no longer works

### ISSUE THREAD

**Issue by KIRA009** [frappe/books#336]
The current api call to `https://api.vatcomply.com/${date}?base=${fromCurrency}&symbols=${toCurrency}` returns a 404 response. This should be changed to `https://api.vatcomply.com/rates?date=${date}&base=${fromCurrency}&symbols=${toCurrency}` according to https://vatcomply.com/documentation#rates-date

**Comment by 18alantom** [comment]
Thanks! why not raise a PR to make the fix?

**Comment by KIRA009** [comment]
Yep, will submit a PR tonight

**Comment by 18alantom** [comment]
Closing cause #340 merged
