### ISSUE TITLE
While starting to install frappe on computer

### ISSUE THREAD

**Issue by AsikRahman** [frappe/books#351]
While starting to install frappe on computer, pop up display show this information
![bug report](https://user-images.githubusercontent.com/100584076/155985319-4edfc092-1386-404c-a866-02aa17a0e80e.jpg)

**Comment by 18alantom** [comment]
Yup this is a known issue on Windows, some apps on running the installer on windows will trigger the SmartScreen. Once sufficient people start using Frappe Books, this dialog should stop showing. (p.s. this doesn't occur on other platforms)

Earlier it used to say that there's a virus in the installer ([issue](https://github.com/frappe/books/issues/282)) which was a false positive. Fortunately, this doesn't occur anymore.

I assure you that Frappe Books is safe to use, so you can click _Run Anyway_ and try it out :)
