### ISSUE TITLE
item input issue and discount colum during invoiceing,

### ISSUE THREAD

**Issue by deepesh1203** [frappe/books#353]
hello, in item master purchase price and selling price are equal ? how is it so,it should differ,both should not be same, also during billing or invoice making discount column need to added.

**Comment by 18alantom** [comment]
The rate in the Item master is the base rate, it can even be zero.

You can set separate values when Billing and Invoicing. Mostly customizations for item valuation (eg separate rates) will be pushed to an inventory plugin.

The discount column makes sense, will add that in an upcoming release.

**Comment by deepesh1203** [comment]
thank you, and hi i want to learn here and help in developing this nice frappe books, can you guide me and teach me,

**Comment by 18alantom** [comment]
Thank you :)

I can answer queries if you have any. Other than that you will have to dive into the code to learn about it, it will be a bit difficult depending on whether you know the tech stack of Frappe Books, but you'll get a hang of it.

Also if you are looking to contribute you should join our TG group: https://t.me/frappebooks
