### ISSUE TITLE
WebDAV support

### ISSUE THREAD

**Issue by vip20** [frappe/books#357]
Amazing application. I felt user should have an option to save his records to a WebDAV like [WebDAV with Box](https://support.box.com/hc/en-us/articles/360043696414-WebDAV-with-Box). I've seen similar approach in an opensource software called [Joplin](https://joplinapp.org/)

**Comment by 18alantom** [comment]
Thanks for the suggestion but won't be doing this any time soon. Wasn't familiar with WebDAV, it seems like an extension over HTTP. May consider it in the future if trying to create a non-local offering of Books.
