### ISSUE TITLE
Chart of Accounts

### ISSUE THREAD

**Issue by oveeriksson** [frappe/books#358]
https://user-images.githubusercontent.com/75839829/156921057-3f64fb71-3eed-40a2-b1a2-fda0cc4ea014.mp4

I can't create a new account. Also, why isn't there a templet for importing Charts of Accounts?

Best Regards, 

Ove Eriksson

ove.eriksson@dahai.se

**Comment by 18alantom** [comment]
Looks like a bug will push a fix soon.

Regarding the chart of accounts template, if you want to add one for your country this is the format: https://github.com/frappe/books/tree/master/fixtures/verified

**Comment by 18alantom** [comment]
Fixed it in this [commit](https://github.com/frappe/books/commit/6912355e6262c53dbe7cb7df3a490d11d7af488f), will be out at the end of the week.
