### ISSUE TITLE
Incorrect Icon size on macos Big Sur or Monterey

### ISSUE THREAD

**Issue by mBilG** [frappe/books#362]
The icon size is bigger than the standard in macos..
I've done a quick and dirty copy of it with the correct space etc..
find it here: 
https://media.macosicons.com/parse/files/macOSicons/e6f7bebc9648672f355626b46a888ea9_Frappe_Books.icns

When I have the time, I'll update it to a proper SVG file (and maybe submit a few designs if you're interested) and share with you..

**Comment by 18alantom** [comment]
Hadn't noticed that, thanks!

Why not raise a PR to fix the icon (since you've found the issue and the fix)?

Also, yup I'm interested in your designs :)

**Comment by mBilG** [comment]
No problem.. will do so once I have some free time..
