### ISSUE TITLE
Sales/Purchases Items not showing

### ISSUE THREAD

**Issue by mBilG** [frappe/books#363]
How to reproduce bug:
1. Open app
2. Create new sales item from Get Started (create item for both sales & purchases)
3. Go to Sales > Sales Items
4. No items appear in list
5. create new item -> other items appear
7. Close side-panel -> existing items disappear again

Same issue with Purchase Items window

**Comment by 18alantom** [comment]
Here, point 5 is a bug, will fix that soon.

The reason why the item doesn't appear under Sales Items is cause **For** may be set to **Both**
![Screen Shot 2022-03-14 at 11 25 07](https://user-images.githubusercontent.com/29507195/158113292-5160df74-8030-4b6f-b420-1a87f53da941.png)

In this case, it should appear under _Common > Common Items_
 
Let me know if this still occurs when **For** is set to **Sales** or **Purchases**.

**Comment by 18alantom** [comment]
(Will close when point 5 is fixed)

**Comment by mBilG** [comment]
> Here, point 5 is a bug, will fix that soon.
> 
> The reason why the item doesn't appear under Sales Items is cause **For** may be set to **Both** ![Screen Shot 2022-03-14 at 11 25 07](https://user-images.githubusercontent.com/29507195/158113292-5160df74-8030-4b6f-b420-1a87f53da941.png)
> 
> In this case, it should appear under _Common > Common Items_
> 
> Let me know if this still occurs when **For** is set to **Sales** or **Purchases**.


You're correct.. it was created For Both Sales and Purchases..
Issue doesn't happen when item is created for only Sales or Purchases..

**Comment by 18alantom** [comment]
Fixed this ([commit](https://github.com/frappe/books/commit/0b59dc74dcf965445dfde475a09b9619632a40de)), will be out in the next release.
