### ISSUE TITLE
Wrong tax label for multi tax items

### ISSUE THREAD

**Issue by 4silvertooth** [frappe/books#365]
If there are multiple rows of item with **different GST tax** slab the final invoice shows tax% of the **first row** item only.
Lets say on first row I have a item with tax slab 18% and second row with tax slab 5% the final invoice _label_ shows 18% as tax although the calculation of the tax is fine according to multiple taxes.

**Comment by 18alantom** [comment]
Thanks for pointing it out! I've removed it from the Print View ([commit](https://github.com/frappe/books/commit/a3e4a7fc3fe46703ffc336c77bae517ccb89ec7d)), will add item wise tax breakdown on a per-row basis.
