### ISSUE TITLE
Business Template for Sales Invoice Missing Notes Section

### ISSUE THREAD

**Issue by gb91757** [frappe/books#376]
Hi,
When I print a sales invoice using the business template the Notes section is missing.  I looked at the Business.vue template and it appears there are some extra `<template>` (line 116) and `</template>` (line 125) tags.  I downloaded the source and removed these tags and all works fine now.  Can this be fixed in a new release please?

[https://github.com/frappe/books/blob/master/models/doctype/SalesInvoice/Templates/Business.vue](url)

Thanks.
Andrew.

**Comment by 18alantom** [comment]
Thanks for the find!

I've pushed a [fix](https://github.com/frappe/books/commit/d3af272bcc5f13a756bcb74f041e3d7fd10bd853). It'll be in the next release.
