### ISSUE TITLE
Update version

### ISSUE THREAD

**Issue by sliine** [frappe/books#377]
Hey, I can write command yarn in directory books and me enetered frappe-books@0.4.3-beta.0: The engine "node" is incompatible with this module. Expected version ">=16.13.1 <17". Got "17.8.0" - this errors, please update version yarn to 1.22

**Comment by 18alantom** [comment]
Hey, this is because of your node version which is at 17.8.0
You can use [`nvm`](https://github.com/nvm-sh/nvm) to set the version to 16

```bash
nvm use 16
```

I have not set any restrictions for yarn. I use yarn version 1.22.18

**Comment by sliine** [comment]
`⠦  Bundling main process...
<--- Last few GCs --->

[30832:0x6725ac0]   175914 ms: Scavenge 501.7 (516.6) -> 501.0 (521.3) MB, 4.6 / 0.0 ms  (average mu = 0.842, current mu = 0.737) allocation failure 
[30832:0x6725ac0]   176595 ms: Mark-sweep 504.8 (521.6) -> 501.0 (522.6) MB, 627.4 / 0.0 ms  (average mu = 0.701, current mu = 0.442) allocation failure scavenge might not succeed
[30832:0x6725ac0]   177418 ms: Mark-sweep 505.7 (522.8) -> 503.7 (525.1) MB, 721.1 / 0.1 ms  (average mu = 0.505, current mu = 0.123) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb09980 node::Abort() [/root/.nvm/versions/node/v16.14.2/bin/node]
 2: 0xa1c235 node::FatalError(char const*, char const*) [/root/.nvm/versions/node/v16.14.2/bin/node]
 3: 0xcf784e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/root/.nvm/versions/node/v16.14.2/bin/node]
 4: 0xcf7bc7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/root/.nvm/versions/node/v16.14.2/bin/node]
 5: 0xeaf465  [/root/.nvm/versions/node/v16.14.2/bin/node]
 6: 0xebf12d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/root/.nvm/versions/node/v16.14.2/bin/node]
 7: 0xec1e2e v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/root/.nvm/versions/node/v16.14.2/bin/node]
 8: 0xe8336a v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/root/.nvm/versions/node/v16.14.2/bin/node]
 9: 0x11fc0b6 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/root/.nvm/versions/node/v16.14.2/bin/node]
10: 0x15f0b19  [/root/.nvm/versions/node/v16.14.2/bin/node]
Aborted
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

I changed version nvm, write command and me entered this errors, how to fix?

**Comment by 18alantom** [comment]
@sliine I've never seen this issue. What are your system's specs? (RAM, processor, OS)

Can you try with node 16.3.1?

**Comment by sliine** [comment]
My OS system specs 2 Core/ 2 GB RAM/ 100 GB HDD. No try with node 16..3.1

> @sliine I've never seen this issue. What are your system's specs? (RAM, processor, OS)
> 
> Can you try with node 16.3.1?

**Comment by 18alantom** [comment]
I don't think it will work using 2 GB RAM, you'll have to upgrade 😅

If any other applications are open, try closing them and then run the command.
