### ISSUE TITLE
After build not show Dashboard page in Ubuntu 20.04 build for Linux

### ISSUE THREAD

**Issue by support-gennextsystems** [frappe/books#382]
After build not show the Dashboard page. build for Linux

![Screenshot from 2022-04-23 13-08-10](https://user-images.githubusercontent.com/92385271/164888261-6ecbe007-1fe0-450e-8340-5590c0fe5df7.png)

But when we click on the sidebar link its shows.

**Comment by Francabicon** [comment]
Try to open the dev tools and see is there any html scripts there

**Comment by support-gennextsystems** [comment]
the problem in the URL **this.winURL = 'app://./index.html';** the application pointing to the URL after build. In development mode, it goes to **http://localhost:8080/**

and the dev tools show a warning **Could not parse content for app://./opt/Frappe**

**Comment by 18alantom** [comment]
fixed in: https://github.com/frappe/books/pull/394
