### ISSUE TITLE
Build ID conflict with ferdi RPM Fedora

### ISSUE THREAD

**Issue by Francabicon** [frappe/books#383]
![image](https://user-images.githubusercontent.com/52349593/165069554-a7e6a371-dd01-45b0-9ffb-3165419908f4.png)
Hi people there seems to be a problem with the build id of the RPM packages when installing on fedora.
They keep stating that there are conflicts with the software of Ferdi. Can anyone advice me on what is going on. Thank you.

**Comment by 18alantom** [comment]
Closing cause [issue and fix seem trivial](https://www.reddit.com/r/Fedora/comments/gn1n5p/buidid_from_install_conflicts_with_file_from/) (if debugging of the packages is not intended).
