### ISSUE TITLE
Edit / Delete Bills after submit

### ISSUE THREAD

**Issue by TomSaw** [frappe/books#384]
I've played around... now my file is poissened with dummy entries 😭

Workaround Pro Tip: Tweak the database. It's very easy even for non-techies.

**Comment by 18alantom** [comment]
You can Cancel the transaction, this is required so that the ledger entries can be invalidated. Will add deletion of cancelled transaction soon.

**Comment by TomSaw** [comment]
Yea found this chancel - feature. Deleting as well is exactly what's missing to me.

**Comment by 18alantom** [comment]
done here: https://github.com/frappe/books/pull/381
