### ISSUE TITLE
Cannot change location of Frappe Books SQLite DB from Deskop to anywhere else in the system

### ISSUE THREAD

**Issue by sodhancha** [frappe/books#385]
**Current version:** _v0.4.3-beta.0_

![Screen Shot 2022-04-28 at 12 01 43](https://user-images.githubusercontent.com/1052091/165689159-cc1b6c39-e547-4afe-9bff-0cb058d93d4d.png)

As seen in the screenshot there is currently no place where we can change the location of the FrappeBooks DB.
The DB gets generated in the Desktop for MacOS.

PFA below screenshot of DB file in desktop

![Screen Shot 2022-04-28 at 12 03 52](https://user-images.githubusercontent.com/1052091/165689462-bf56f1fe-1169-440a-b9b4-469f88eb9fbd.png)

**Comment by 18alantom** [comment]
Hey, you can move the db file wherever you'd like, then just select it using the green option: 
![Screen Shot 2022-04-28 at 13 36 43](https://user-images.githubusercontent.com/29507195/165707058-e45b89a9-fdbe-414b-ac4d-68e3cf91969e.png)

**Comment by sodhancha** [comment]
@18alantom can you direct me to this menu ?
I cannot seem to find the panel you mentioned in your screenshot.

**Comment by 18alantom** [comment]
https://user-images.githubusercontent.com/29507195/165716334-66a682ff-2e9c-4933-a68b-5186d1128512.mov

Sure. If it doesn't detect your db file, it will automatically open this window.
