### ISSUE TITLE
Invalid currency code 'KZ'

### ISSUE THREAD

**Issue by devmiguelpereira** [frappe/books#386]
<h2>Invalid currency code 'KZ'</h2>
When trying to create a organization with the field Angola as the country and KZ as the currency it throws an error of invalid currency code 'KZ'

![invalid currency code kz](https://user-images.githubusercontent.com/50536010/167342279-8f0b64f1-f191-41af-a63e-fe1f8067cf07.png)

**Comment by 18alantom** [comment]
Try entering the ISO 4217 code **AOA**.

The KZ as currency code seems to be incorrect, will fix it in this [PR](https://github.com/frappe/books/pull/381).

**Comment by devmiguelpereira** [comment]
Great, thanks for the quick reply.

I entered the ISO 4217 code AOA and it worked fine.

Thank you a lot for the help!
