### ISSUE TITLE
Dutch translation frappe/books

### ISSUE THREAD

**Issue by FastAct** [frappe/books#388]
added Dutch translation
[nl.csv](https://github.com/frappe/books/files/8729144/nl.csv)

**Comment by 18alantom** [comment]
Thanks a lot! I've [committed](https://github.com/frappe/books/pull/381/commits/974275625437a687388f292cd8dd45fc64f197e7) your translations, it'll be added once that PR is merged.

I added it to the PR cause there were some formatting updates in the language csv files.

**Comment by 18alantom** [comment]
done here: https://github.com/frappe/books/pull/381
