### ISSUE TITLE
Pull Request is not being allowed to be done

### ISSUE THREAD

**Issue by talmax1124** [frappe/books#389]
Hello, I did the spanish translation, with the file esp.csv in the repository,[ ](https://github.com/talmax1124/books). How could I add the Spanish csv?

**Comment by 18alantom** [comment]
![Screen Shot 2022-05-23 at 15 46 36](https://user-images.githubusercontent.com/29507195/169798126-9041b6c0-67cf-47c6-baa1-e92187e60079.png)

You'll have to click on the green **Create pull request** button ([link](https://github.com/frappe/books/compare/master...talmax1124:master)). (docs [ref](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork))



Just a heads up, a few changes will have to be made cause there's a slight update in the format:
- trailing commas will have to be removed
- the format has switched to regular CSV, i.e. no backticks for example check [this](https://github.com/frappe/books/pull/381/commits/974275625437a687388f292cd8dd45fc64f197e7) file

I don't mind making the changes, will do so once you raise the PR.


Also thanks for doing the translations! :)

**Comment by talmax1124** [comment]
@18alantom, I did the PR. If you could do it, I will appreciate it. I won't have time to do it for a while. #391

**Comment by 18alantom** [comment]
Merged, will fix the formatting in #381 

(also filename will be changed to `es.csv`)

edit: [formatting fixed](https://github.com/frappe/books/pull/381/commits/5027c0c81f4ae664f0b7c35d086da1c1561ee538)
