### ISSUE TITLE
Latest version no longer shows the customer address in invoices

### ISSUE THREAD

**Issue by gb91757** [frappe/books#402]
<h2>Description</h2>
Latest version no longer shows the customer address in invoices as in previous versions

**Version**: `0.5.0-beta.0`
**Path**: `/print/SalesInvoice/SINV-1010`

**Comment by 18alantom** [comment]
Fixed in this commit: [fix: party address doesn't show in print](https://github.com/frappe/books/commit/82336e18bc4de8cd68df47c43c90cc1cd08aaac5)
