### ISSUE TITLE
Add Bikram Sambat aka Nepali Calender Datepicker to Frappe Books 

### ISSUE THREAD

**Issue by sodhancha** [frappe/books#403]
### Feature request:

Bikram Sambat is the prevelant calender currently used in [Nepal](https://en.wikipedia.org/wiki/Nepal). Even though not ideal and legacy we still have to use it for doing business in Nepal including generating [Tax Invoices](https://nepal.gov.np:8443/NationalPortal/view-page?id=94), Filing Taxes, Registering a company and any kind of compliance, tax or financial matters.

Logic for Bikram Sambat to A.D conversion is provided below in a jQuery plugin.
Hope someone from frappe team looks into Multi-Calendering and fixing [Fiscal year ends according to that calender](https://en.wikipedia.org/wiki/Fiscal_year#Nepal) rather than A.D Calender. 

**Logic provided here:**
[https://github.com/leapfrogtechnology/nepali-date-picker](https://github.com/leapfrogtechnology/nepali-date-picker)

**Bikram Sambat wiki page:**
[https://en.wikipedia.org/wiki/Vikram_Samvat](https://en.wikipedia.org/wiki/Vikram_Samvat)

**Comment by 18alantom** [comment]
@sodhancha I won't have the bandwidth to work on this, but I'll be more than happy to review your PR if you were to push it with this feature.
