### ISSUE TITLE
JOURNAL ENTRY

### ISSUE THREAD

**Issue by PAULPROSSER** [frappe/books#412]
<h2>Cant scroll down, cant see the total debit , credit</h2>

After few rows the total debit and credit cant be seen
you cant scroll down to correct things
I will be preferable that the software just sum up the total debit and credit automatically 
but not always  adjusting it when you fill one way to the other 

**Version**: `0.5.0-beta.0`
**Path**: `/edit/JournalEntry/2ptotn-l51qwfnd`

**Comment by 18alantom** [comment]
Hey, can you send me a screen capture and tell me what platform you're on?

https://user-images.githubusercontent.com/29507195/177773410-721b5fc1-8802-485b-838d-2039ee0de8b7.mov

 It seems to be working for me

**Comment by 18alantom** [comment]
Closing this cause may have been solved in the new UI update. (well I can't seem to replicate it)
