### ISSUE TITLE
DB issue

### ISSUE THREAD

**Issue by harjit8016** [frappe/books#417]
<h2>Description</h2>
Add some description...

<h2>Error Info</h2>

**Error**: _DatabaseError: Error
ENOENT: no such file or directory, copyfile '/Users/harjitsingh/Documents/books.db' -> '/Users/harjitsingh/Documents/__premigratory_temp.db'_

**Stack**:
```
Error: ENOENT: no such file or directory, copyfile '/Users/harjitsingh/Documents/books.db' -> '/Users/harjitsingh/Documents/__premigratory_temp.db'
```

**Version**: `0.6.0-beta.0`
**Platform**: `darwin`
**Path**: `/`

**Comment by 18alantom** [comment]
Missing `books.db` indicates the file may have been deleted before copying occurs.

If this reoccurs try creating a new instance (I'm guessing `books.db` was an evaluation instance).

Closing cause can't replicate naturally.
