### ISSUE TITLE
Date picker during file creation

### ISSUE THREAD

**Issue by rg8032** [frappe/books#422]
The date picker for fiscal year start/end dates behaves strangely while creating a new database.  I am unable to get through the creation process.  I can't select most of the top half of dates.  If I attempt to change a previously selected date, the date picker ends up with one or two rows that have >7 days.
![image](https://user-images.githubusercontent.com/5965422/179991933-1d6d8d6b-db27-43b5-85f6-5985730ec93a.png)

**Comment by 18alantom** [comment]
@rg8032 can you attach a screen capture of the date picker issue.

I'm unable to replicate it on the latest version, it's working properly for me.

**Comment by rg8032** [comment]
https://user-images.githubusercontent.com/5965422/180052519-c70ac446-6c24-49ca-9038-6cc68e23091b.mp4

**Comment by rg8032** [comment]
I am using 0.6.0-beta.1 in the video.  The installer version for Windows 10 (not the portable version.  I had similar issues with the portable version.  The same thing in version 5.  The issue was not present in the v0.0.3 that I also have installed. 

EDIT: version number was wrong.  It read "6.0.0-beta.1".

**Comment by 18alantom** [comment]
I'm still unable to replicate the exact issue, but the Date Picker does seem to be broken on the Setup version. (It's working properly for me on the portable)

Looking into it.

**Comment by rg8032** [comment]
I setup a development environment to try to debug the issue a little.  I have virtually no familiarity with Vue or JS but a decent amount of experience elsewhere.

My understanding is that Vue requires a unique 'key' when generating lists.  Duplicate keys cause 'render errors' according to Vue's documentation for 'key'.  I believe that is what is occurring.  I am still not sure why.  The datesAsWeeks callback seems to produce sane output.  

Upon initially triggering the DatePicker to open, it appears and operates normally.  Upon paging to the previous month, the output is:
![image](https://user-images.githubusercontent.com/5965422/181096352-8748b908-2c9a-49bf-bebb-22ac1e396a10.png)

This error continues to compound adding one or more 'extra' dates and causing other strange behavior.

The following warning message is produced in the console log of the packaged browser's developer tools:

> [Vue warn]: Duplicate keys found during update: "2022-06-06" Make sure keys are unique. 
>   at <Popover onOpen=fn< bound selectCurrentMonthYear> > 
>   at <DatePicker ref="input" input-class= (2) [Array(4), 'cursor-text'] value="2022-06-13"  ... > 
>   at <Date size="small" df= {fieldname: 'fiscalYearEnd', label: 'Fiscal Year End Date', placeholder: 'Fiscal Year End Date', fieldtype: 'Date', required: true} value="2022-06-13"  ... > 
>   at <FormControl ref_for=true ref="controls" size="small"  ... > 
>   at <TwoColumnForm doc= SetupWizard {_map: Map(0), _isHot: Map(0), _eventQueue: Map(0), _listeners: Map(1), _onceListeners: Map(0), …} > 
>   at <Slide primary-disabled=false onPrimaryClicked=fn< bound handlePrimary> onSecondaryClicked=fn< bound handleSecondary> > 
>   at <SetupWizard key=3 onSetupComplete=fn< bound setupComplete> onSetupCanceled=fn< bound showDbSelector> > 
>   at < App> 
>   at < App>
> warn @ runtime-core.esm-bundler.js:38
> patchKeyedChildren @ runtime-core.esm-bundler.js:5880
> patchChildren @ runtime-core.esm-bundler.js:5728
> processFragment @ runtime-core.esm-bundler.js:5432
> patch @ runtime-core.esm-bundler.js:5026
> patchBlockChildren @ runtime-core.esm-bundler.js:5350
> patchElement @ runtime-core.esm-bundler.js:5258
> processElement @ runtime-core.esm-bundler.js:5113
> patch @ runtime-core.esm-bundler.js:5030
> patchKeyedChildren @ runtime-core.esm-bundler.js:5809
> patchChildren @ runtime-core.esm-bundler.js:5728
> processFragment @ runtime-core.esm-bundler.js:5432
> patch @ runtime-core.esm-bundler.js:5026
> patchBlockChildren @ runtime-core.esm-bundler.js:5350
> processFragment @ runtime-core.esm-bundler.js:5413
> patch @ runtime-core.esm-bundler.js:5026
> patchBlockChildren @ runtime-core.esm-bundler.js:5350
> patchElement @ runtime-core.esm-bundler.js:5258
> processElement @ runtime-core.esm-bundler.js:5113
> patch @ runtime-core.esm-bundler.js:5030
> componentUpdateFn @ runtime-core.esm-bundler.js:5655
> run @ reactivity.esm-bundler.js:185
> instance.update @ runtime-core.esm-bundler.js:5689
> callWithErrorHandling @ runtime-core.esm-bundler.js:155
> flushJobs @ runtime-core.esm-bundler.js:396
> Promise.then (async)
> queueFlush @ runtime-core.esm-bundler.js:285
> queueJob @ runtime-core.esm-bundler.js:279
> (anonymous) @ runtime-core.esm-bundler.js:5687
> triggerEffect @ reactivity.esm-bundler.js:394
> triggerEffects @ reactivity.esm-bundler.js:384
> trigger @ reactivity.esm-bundler.js:352
> set @ reactivity.esm-bundler.js:523
> set @ runtime-core.esm-bundler.js:3158
> open @ Popover.vue:102
> togglePopover @ Popover.vue:93
> onFocus @ DatePicker.vue:10
> callWithErrorHandling @ runtime-core.esm-bundler.js:155
> callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
> invoker @ runtime-dom.esm-bundler.js:369

I am running 0.6.1-beta.0.   I git pulled master this morning at 10:00 a.m. EDT.

**Comment by 18alantom** [comment]
@rg8032 can you pull and check if this works for you: https://github.com/frappe/books/commit/c0c3046c2092a9c198ebc2ebb82c4d691d2addca

Duplicate key was one of the issues, thanks for finding it :)
