### ISSUE TITLE
screen resolution issue

### ISSUE THREAD

**Issue by test2a** [frappe/books#430]
my current resolution is 1280x720. i am using appimage and the screen does not enjoy scrolling particularly in the create company page.

i have to use tab and scroll to reach the "create company"  button.

**Comment by test2a** [comment]
ok. when i set my resolution to 1366x768, i am able to see the button but not on 1280

**Comment by 18alantom** [comment]
Frappe Books initial resolution is 1200x800. But, since I've enabled resizing (https://github.com/frappe/books/commit/0e37f0073e866d1f3b9bbee822512409e4634489) this shouldn't be an issue, hence closing.
