### ISSUE TITLE
Cannot modify invoice's item

### ISSUE THREAD

**Issue by magixus** [frappe/books#433]
<h2>Description</h2>
Add some description...

**Version**: `0.6.0-beta.1`
**Platform**: `linux`
**Path**: `/edit/SalesInvoice/SINV-1001`

**Comment by 18alantom** [comment]
This is expected behavior, you can't edit an Invoice's Item after it has been submitted.

check this for more info: [doc entry](https://docs.frappebooks.com/transactions/transactional-entries.html#states-of-a-transactional-entry)

**Comment by magixus** [comment]
thanks @18alantom
