### ISSUE TITLE
not for profit reports/settings

### ISSUE THREAD

**Issue by test2a** [frappe/books#435]
not for profit organizations would use books but there would require some changes in reports and maybe in the structure of the accounting.

income and expenditure account (profit and loss account)
receipt and payment account (cash and bank account with p&l)
option to disable sales/purchases
option to rename debtors as donors
gst would be disabled if we dont enter GSTIN so that is already solved.

some more improvements but these should be enough to get started

**Comment by 18alantom** [comment]
Closing this cause the [Chart of Accounts](https://docs.frappebooks.com/miscellaneous/chart-of-accounts.html) renders the first four points invalid.

Point 3: not strictly required.
Point 4: Donors can be created under Accounts Receivable.

**Comment by test2a** [comment]
@18alantom https://khatabook.com/blog/receipt-and-payment-account/

i dont think frappe books has this report as of now
