### ISSUE TITLE
DB Error on making a premigratory db copy

### ISSUE THREAD

**Issue by aakvatech** [frappe/books#437]
<h2>Description</h2>
Add some description...

<h2>Error Info</h2>

**Error**: _DatabaseError: Error
ENOENT: no such file or directory, copyfile 'C:\Users\Mitesh\OneDrive\Documents\frappe-books 2020 01052020.db' -> 'C:\Users\Mitesh\OneDrive\Documents\__premigratory_temp.db'_

**Stack**:
```
Error: ENOENT: no such file or directory, copyfile 'C:\Users\Mitesh\OneDrive\Documents\frappe-books 2020 01052020.db' -> 'C:\Users\Mitesh\OneDrive\Documents\__premigratory_temp.db'
```

**Version**: `0.6.1-beta.0`
**Platform**: `win32`
**Path**: `/index.html`

**Comment by 18alantom** [comment]
Hey, @aakvatech can you give more information regarding this error:
- Does the file `frappe-books 2020 01052020.db` exist?
- Can you still access the database file?
- If not were you able to access the database file earlier?
- Which version of Frappe Books was used to create the file?

(same as https://github.com/frappe/books/issues/417)

**Comment by 18alantom** [comment]
Closing this cause no reply (hence no way to debug)
