### ISSUE TITLE
When running reports, getting type error

### ISSUE THREAD

**Issue by krishnasoyjaudah** [frappe/books#439]
<h2>Description</h2>
Error when running reports

<h2>Error Info</h2>

**Error**: _TypeError: Cannot set properties of undefined (setting 'valueMap')_

**Stack**:
```
TypeError: Cannot set properties of undefined (setting 'valueMap')
    at _ (app://./js/index.0e127820.js:1:450739)
    at Proxy._getAccountTree (app://./js/index.0e127820.js:1:447020)
    at async Proxy.setReportData (app://./js/index.0e127820.js:1:469471)
    at async Proxy.setReportData (app://./js/index.0e127820.js:1:351496)
    at async Proxy.activated (app://./js/index.0e127820.js:1:350524)
```

**Version**: `0.6.1-beta.0`
**Platform**: `win32`
**Path**: `/report/TrialBalance`

**Comment by krishnasoyjaudah** [comment]
After creating transactions, the reports do not update. Must re open the db to see changes

**Comment by 18alantom** [comment]
@krishnasoyjaudah can you provide some steps to recreate both the issues?

It seems to be working correctly for me ([0.6.2-beta.0](https://github.com/frappe/books/releases/tag/v0.6.2-beta.0)).

**Comment by krishnasoyjaudah** [comment]
Steps:
1. Create journal entries, add opening balances. 
2. Run reports

**Comment by 18alantom** [comment]
@krishnasoyjaudah I am still unable to replicate it. Does it work for you in the latest version?

If not can you send a screenshot of your Journal Entry, or replicate the issue and send me the database (zip it and drag it into the edit box of the issue)?

**Comment by 18alantom** [comment]
Closing this cause no reply
