### ISSUE TITLE
Error Creating DB when Language (German) is set

### ISSUE THREAD

**Issue by MusMuss1** [frappe/books#445]
<h2>Description</h2>

You cannot create a new DB if German is selected as language. After switching to English (default) it works again. 
Tested with Windows 11 and MacOS 12.

**Version**: `0.6.2-beta.0`
**Platform**: `win32`
**Path**: `/get-started`

**Comment by 18alantom** [comment]
Should be fixed in: [v0.6.3-beta.0](https://github.com/frappe/books/releases/tag/v0.6.3-beta.0)
