### ISSUE TITLE
Default naming series  provision

### ISSUE THREAD

**Issue by ankitadudakiya** [frappe/books#448]
While creating the transaction I have to select the required naming series each time, If missed the transaction gets created in default system's naming series which is very frustrating. 

<img width="357" alt="image" src="https://user-images.githubusercontent.com/106796221/185197087-b53cf7e0-8d8e-449e-9e5c-a72339aa9271.png">

It should automatically select the last used series or else, We should have some provision to set the default naming series for the transactions

**Comment by ankitsinghaniyaz** [comment]
Yes, this is a big issue. I've had to delete the invoice and create it so many times just because I picked the wrong default series.

The easiest hotfix would be to be able to delete a series but as a book goes into a multiyear thing that would again be a problem.
