### ISSUE TITLE
UX: mandatory field and missing freeze message

### ISSUE THREAD

**Issue by ankush** [frappe/books#449]
- [ ] Email field is mandatory but not clearly shown and submit button is grayed out.
- [ ] When I press submit, it waits for ~15 seconds... maybe add progress or some freeze message at least so the user knows something is being done and it's not stuck. This was on 10 year old i5 linux laptop, so maybe it's just my machine but eh that is the target audience!

![image](https://user-images.githubusercontent.com/9079960/185955690-e1c1bb7c-55f8-429c-94f5-4de17017ddd4.png)

---

**Comment by ankush** [comment]
Also, why is email mandatory in first place? :thinking: 

#freedom from cloud plz :grimacing:

**Comment by 18alantom** [comment]
The 15s loading seems to occur only on Linux for some reason. needs investigation
