### ISSUE TITLE
UX: item creation

### ISSUE THREAD

**Issue by ankush** [frappe/books#450]
- [x] no mandatory indication on any fields.
- [x] Type select element shows `type` for some reason? It should just be 2 options?

![image](https://user-images.githubusercontent.com/9079960/185957920-5fef1b9f-8e1f-4559-b4a2-307eb64e79bf.png)

![image](https://user-images.githubusercontent.com/9079960/185958105-c3065f6c-c85f-44e4-bc6d-83dff7dea980.png)

**Comment by 18alantom** [comment]
[Fixed](https://github.com/frappe/books/pull/567/files#diff-dfae19cf313d6bd6eacb9feb268120df445d6c9d52e4bba0ddfb4dcffd84ffd2L26), disabled option was being used as the field label. Now it shows only if the label isn't shown.
