### ISSUE TITLE
cancelled invoices can be edited

### ISSUE THREAD

**Issue by ankush** [frappe/books#455]
I am not sure if this is intentional, but AFAIK anything after submission shouldn't be editable (or should have an edit trail)

https://user-images.githubusercontent.com/9079960/185966401-cb0e09b9-764d-47fe-9c4f-eb2cb8e0a39c.mp4

**Comment by 18alantom** [comment]
fixed: https://github.com/frappe/books/commit/18d3bbf9595e5b91365aa7aca89c0b85b87e73a0
