### ISSUE TITLE
Cannot view added Description for items at invoice in invoice print 

### ISSUE THREAD

**Issue by ankitadudakiya** [frappe/books#462]
<h2>Cannot view added Description for items at invoice in invoice print </h2>
selected item added Description and saved but on print I can see only item name in print, cannot see added desc in invoice print 

**Version**: `0.6.3-beta.0`
**Platform**: `darwin`
**Path**: `/list/SalesInvoice`
**Language**: `undefined`
**Country**: `in`

**Comment by 18alantom** [comment]
Description is not shown in the templates by default, you should be able to add it in a custom template using the Template Builder once it's out.
