### ISSUE TITLE
Add invoice due date

### ISSUE THREAD

**Issue by rosjum** [frappe/books#467]
Invoices look beautiful, but currently the invoice does not have the invoice due date field. It may be considered an important information on an invoice.

**Comment by parajulizRoman** [comment]
Exactly, bills are due for weeks and months in current market practice. Sending party an auto email / whatsapp message with details regarding due amount will be 🤯.

**Comment by rosjum** [comment]
Hi Alan @18alantom, any update on this please? This is the main reason I am not able to adapt this application. Having a due date on invoices will make life so much easier. Is there a doc.dueDate key that I can use in the meantime in a custom invoice template to get the due date for an invoice?

**Comment by mildred** [comment]
It is always possible to add the due date to the invoice notes and shown in the correct place in the invoice template, but I agree this is not for the best.

An easy solution could be to add custom fields to invoices, and allow the template to display them.

Better solution would be to include due date and compute it based on set of rules, or set manually.

**Comment by 18alantom** [comment]
@rosjum you can add it as a Custom Field: [Customize Form documentation](https://docs.frappebooks.com/miscellaneous/customize-form.html)

**Comment by rosjum** [comment]
Thanks @mildred @18alantom. 

@parajulizRoman that is a great suggestion, but not sure if it is likely to go on the roadmap in near future.
