### ISSUE TITLE
Marking invoice as paid, Value Missing error from field that doesn't exist

### ISSUE THREAD

**Issue by Shrinks99** [frappe/books#473]
When attempting to mark an invoice as paid on the Sales Invoices > 3 dots > Make Payment option, the application errors and does not allow me to complete the form.  My assumption is that the logic that is supposed to auto-handle the "from account" (as this is a known value... or at least it should be) is missing and it doesn't correctly pick it up from the current invoice we're marking.

<img width="738" alt="Screen Shot 2022-10-05 at 12 27 43 AM" src="https://user-images.githubusercontent.com/5672810/193981896-26a75e01-b137-462b-884a-96fa9b005ce1.png">

Version 0.6.6-beta.0
macOS 12.6

**Comment by Shrinks99** [comment]
This is notably _not_ an issue with the "new sales payment" flow which is an alternate way of going about things in the meantime until this bug is fixed :)

<img width="355" alt="Screen Shot 2022-10-05 at 12 34 57 AM" src="https://user-images.githubusercontent.com/5672810/193982073-b6644bb8-53ad-4ead-8ebe-fa5dd236bef6.png">

**Comment by 18alantom** [comment]
fixed in https://github.com/frappe/books/commit/7c03b98d6796b06714a35dcead4c9cee3756d50e
