### ISSUE TITLE
The Payment functionality works only when we select cash. Issue when we select our Bank account 

### ISSUE THREAD

**Issue by ClaudeErpSystem** [frappe/books#475]
<h2>Description</h2>
Add some description...

**Version**: `0.6.6-beta.0`
**Platform**: `win32`
**Path**: `/edit/SalesInvoice/SINV-1285?edit=1

Hi 

I tested your new Frappe-Book 0.6.6 beta on Windows 10 and MX Linux 21.
I tested your new currency functionality. It is working as expected. Good job.

**The issue I have is related to the Payment option:**
If we select (1) Check and (2)  the Bank account, I am getting the following error : 
**Mandatory Error: Value missing for From Account**

[2022-10-06 - Frappe_Books_error_Rel_0.6.6-Beta.pdf](https://github.com/frappe/books/files/9730102/2022-10-06.-.Frappe_Books_error_Rel_0.6.6-Beta.pdf)

**_Please note that I don't have this issue in release 0.6.5. I am able to make payment with the Check option._**
**Note:** By looking at your database demo, I found that all of your payments are Cash, maybe this is why you don’t have this issue during your unit testing. If you try doing a Payment using the Check option, you should be able to reproduce this issue in 0.6.6-beta.

[Bank_entries_information.pdf](https://github.com/frappe/books/files/9733794/Bank_entries_information.pdf)

Thanks for this great accounting software. It is well designed and it is easy to use.

Regards
Claude

**Comment by 18alantom** [comment]
hey @ClaudeErpSystem thanks for the elaborate issue breakdown, it's been fixed in https://github.com/frappe/books/commit/7c03b98d6796b06714a35dcead4c9cee3756d50e
