### ISSUE TITLE
Cannot pay two invoices with one check ID

### ISSUE THREAD

**Issue by ClaudeErpSystem** [frappe/books#476]
<h2>Description</h2>
Add some description...

**Version**: `0.6.5`
**Platform**: `win32`
**Path**: `/list/Payment/paymentType/Pay/Purchase Payments?edit=1

I can't pay two bills in the amount of $85.00 with one check number. I will have to write two checks to pay two bills.

**_Here are my screenshots for more information about this issue._**
[Issue - Cannot pay two invoices with one check ID.pdf](https://github.com/frappe/books/files/9735093/Issue.-.Cannot.pay.two.invoices.with.one.check.ID.pdf)

Thanks

**Comment by 18alantom** [comment]
once again thanks for the elaborate report it's been fixed in https://github.com/frappe/books/commit/5f937b041b7a5641932249ada1a2eb8eb26a82a1

**Comment by 18alantom** [comment]
https://github.com/frappe/books/releases/tag/v0.6.6
