### ISSUE TITLE
Payments Improvement in Frappe-Book

### ISSUE THREAD

**Issue by ClaudeErpSystem** [frappe/books#481]
<h2>Description</h2>
**Note**: `This is not a bug, this is an improvement for Frappe-Book software with the payment option.`

**Version**: `0.6.6`
**Platform**: `win32`
**Path**: `/list/Payment/paymentType/Pay/Purchase Payments?edit=1

If I go to the Purchase Payments menu to perform one payment of two unpaid invoices for the same vendor.
When I complete the payment for the above two invoices, the list of all my invoices are listed (Paid and Unpaid).

...**_Only the unpaid invoices should be displayed from the drop box invoices payment menu._**

Please have a look at my detailed PDF file.
[2022_10_12 - Payments Improvement in Frappe-Book.pdf](https://github.com/frappe/books/files/9768772/2022_10_12.-.Payments.Improvement.in.Frappe-Book.pdf)

**Here is the SQLs for the DropDown lists:**
-- For Purchase Invoices payment module 
SELECT name
FROM PurchaseInvoice
WHERE party =  ' Selected Supplier name from the Payment form '
AND submitted = 1
AND cancelled = 0
AND ROUND(outstandingAmount,2) <> 0.00
ORDER BY Name ASC ;

-- For Sales Invoices payment module 
SELECT name
FROM SalesInvoice
WHERE party = ' Selected Client name from the Sales form '
AND submitted = 1
AND cancelled = 0
AND ROUND(outstandingAmount,2) <> 0.00
ORDER BY Name ASC ;

Thanks
Regards

**Comment by 18alantom** [comment]
fixed: https://github.com/frappe/books/commit/87971b8a6ba6fd0683c5293f6c6d542f81558f31

Thanks for the detailed issue, it actually turned out to be a bug. Caused cause currency values are stored as strings and so numeric comparators don't work as expected.
