### ISSUE TITLE
Lost some Purchase Invoice Item and Sales Invoice Item After Upgrade to 0.6.6

### ISSUE THREAD

**Issue by smalldale** [frappe/books#483]
# NotFound: Account Write Off 
I tried upgrade it with my database from 0.6.5 and failed. When I use 0.6.5 it get the same error but can bypass it without any modification on the database.
![image](https://user-images.githubusercontent.com/49019693/195670603-1f6ffa59-99cb-49aa-8da4-b71a9298e9f0.png)

I solved with db browser, by delete record `writeOffAccount` in `SingleValue` table, because I don't want to set write off account.
![image](https://user-images.githubusercontent.com/49019693/195671625-5c853d57-fd16-472e-9e05-0f0513194b18.png)

# Sales and Purchase Invoice Item Problem
Some item in Sales and Purchase Invoice got remove after open 0.6.6, it's all fine when open 0.6.5 after db change. It still show the grand total of the invoice.
![image](https://user-images.githubusercontent.com/49019693/195678688-8f74ca73-a21e-4366-aae8-2c63fe9155a9.png)
![image](https://user-images.githubusercontent.com/49019693/195678932-fbac1d0c-c45f-437e-ba9c-b5d6249ed766.png)

### Here's what is look like on db browser.
On the left is `PurchaseInvoiceItem` before open 0.6.6 (443 records) and the right is after open 0.6.6 (201 records).
![image](https://user-images.githubusercontent.com/49019693/195679628-f6f0559a-4f6c-49d7-bb65-5677b4f68b8a.png)

On the left is `SalesInvoiceItem` before open 0.6.6 (662 records) and the right is after open 0.6.6 (201 records).
![image](https://user-images.githubusercontent.com/49019693/195679989-5fc32fc1-a6f4-451e-9a75-6c41f5c01db5.png)

**Comment by 18alantom** [comment]
@smalldale can you tell me what Chart of Accounts you are using? Not setting a Write Off account might cause errors later on.

As for the second issue, do you have any steps so that I can replicate it?

**Comment by 18alantom** [comment]
The second issue has been fixed: https://github.com/frappe/books/commit/2efc2908fcef4291b5336075922d3867bac05894

**Comment by smalldale** [comment]
@18alantom 

Indonesia Chart of Accounts, I use the same db since 0.3.0 beta1.

**Comment by 18alantom** [comment]
The first issue has been fixed: https://github.com/frappe/books/commit/3b229321a9bd6a2823492bfad52f9c3cf0da0bcf

It should now show a more sensible error message. This occurs because the **Write Off Account** set in General Settings (under Setup) does not exist, setting an account that exists should solve the problem.
