### ISSUE TITLE
not correct currency symbol

### ISSUE THREAD

**Issue by rickysut** [frappe/books#485]
<img width="606" alt="Screen Shot 2022-10-19 at 19 17 15" src="https://user-images.githubusercontent.com/27186274/196688954-e7a24670-cc77-42d8-98e3-f88739e57bfe.png">
Hello,

i found journal entry list use Indian Currency meanwhile Total Debit and Credit using my country Currency Rp.

anyone got same problem with me?

**Comment by 18alantom** [comment]
fixed: https://github.com/frappe/books/commit/4646049ad88dc8704fd08db93e6569cc232a73dd
