### ISSUE TITLE
Possibility to read via API ERPNEXT site

### ISSUE THREAD

**Issue by Helkyd** [frappe/books#488]
Hi all,
Not an issue but i wonder if would be possible to give a URL for an ERPNEXT site and the app Read/View Invoices to start.

Thanks

**Comment by 18alantom** [comment]
What is the use case here?

Closing Because: Interoperability with ERPNext doesn't make much sense as both ERPNext and Frappe Books are for different kinds of users medium to large businesses vs small businesses.
