### ISSUE TITLE
Duplicate Journal Error 0.7.0

### ISSUE THREAD

**Issue by smalldale** [frappe/books#493]
I performed this on demo database, but same problem happen with my database too.
Windows 10 21H2, 0.7.0
# Duplicate Journal Error
I tried to duplicate journal entry, all value is not duplicated and can't save it.

Steps:
1. Create demo database
2. Duplicate Journal Entry
3. Save

![image](https://user-images.githubusercontent.com/49019693/200104908-1c4125ab-5068-4086-943b-2dc225aab0ef.png)
![image](https://user-images.githubusercontent.com/49019693/200104955-80e42968-d18e-4d33-8f0c-ad35a64f2a9e.png)

# Closing Cr Dr on Trial Balance
All 0 on Closing Debit and Credit.
![image](https://user-images.githubusercontent.com/49019693/200105188-ed45f79e-d71e-4fec-a96f-9dc82739717d.png)

**Comment by 18alantom** [comment]
Thanks for raising the issue

Fixed Duplicate Journal Error: https://github.com/frappe/books/commit/57699009bf056c948189d15a549283455ba87052

The closing amounts are all zero because the entered range (current fiscal year) hasn't ended, so the books haven't been closed.
