### ISSUE TITLE
DB unusable after version update (HELP!)

### ISSUE THREAD

**Issue by raul-castillo** [frappe/books#494]
<h2>Errors everywhere, HELP!</h2>

I began using Frappe Books in November 2021 when I started to rent my apartment on Airbnb.

It's been nice having a simple little app where I can keep my accounting and operation insights, and I had been using version 0.4.2 beta for around 10 months, that's until a couple of months ago (end of August) when I tried the first release out of beta, which I guess did some big changes to the DB structure or something, and basically rendered my instance of the app and my data useless.

I tried to go back to the 0.4.2 version I had been using, but the data won't even load at all.

I tried to give it some time and wait for subsequent updates to see if the issue got fixed, but no luck still.

I have just tried 0.7.0 and even though the rendering of the data has gotten better, I still can't even "open/view" my sales/purchase invoices, payments, customers/suppliers, items, etc. The only thing I can "open/view" are basically Journal Entries.

Everytime I try to "open/view" something like an invoice, I always get an "invalid input" error followed by a bunch of numbers and then at the send something about a "string".

I'm now almost 3 months behind on my accounting and I don't know what to do about it.

Any help would be kindly appreciated, guys.

Thank you in advance!

<h2>Error Info</h2>

**Error**: _Error: invalid input '7694.249999999985172.231984.912068.942124.82124.82488.1211943.52-2123.32-5172.23-1984.91-2068.94-2124.8-2124.8-2488.12-11943.522124.81664.714526.692137.351653.543208.091970.732054.168244.126625.852897.961679.33-2124.8-1664.71-4526.69-2137.35-1653.54-3208.09-1970.73-2054.16-8244.12-6625.852000.391972.633528.683723.223695.463881.725445.811972.632056.141655.873750.97-2897.96-1679.33-2000.39-1972.63-3528.68-3723.22-3695.46-3881.72-5445.81-1972.63-2056.14-1655.871743.451743.451977.253704.111663.411663.413592.581977.251977.253536.942562.222785.041977.251896.231799.11665.361665.36-3750.97-1743.45-1743.45-1977.25-3704.11-1663.41-1663.41-3592.58-1977.25-1977.25-3536.94-2562.22-2785.04-1977.25-1896.23-1799.1-1665.363586-35861733.33-1733.333705.5119781744.111744.113928.411680.881854.952256.81931.613208.69-1665.36-3705.51-1978-1744.11-1744.11-3928.41-1680.88-1854.95-2256.8-1931.61-3208.691813.452061.741220.683740.884103.666968.522261.362261.364103.661745.432261.364103.66-1813.45-2061.74-1220.68-3740.88-4103.66-6968.52-2261.36-2261.36-4103.66-1745.43-2261.36-4103.662272.12' of type 'string'_

**Stack**:
```
Error: invalid input '7694.249999999985172.231984.912068.942124.82124.82488.1211943.52-2123.32-5172.23-1984.91-2068.94-2124.8-2124.8-2488.12-11943.522124.81664.714526.692137.351653.543208.091970.732054.168244.126625.852897.961679.33-2124.8-1664.71-4526.69-2137.35-1653.54-3208.09-1970.73-2054.16-8244.12-6625.852000.391972.633528.683723.223695.463881.725445.811972.632056.141655.873750.97-2897.96-1679.33-2000.39-1972.63-3528.68-3723.22-3695.46-3881.72-5445.81-1972.63-2056.14-1655.871743.451743.451977.253704.111663.411663.413592.581977.251977.253536.942562.222785.041977.251896.231799.11665.361665.36-3750.97-1743.45-1743.45-1977.25-3704.11-1663.41-1663.41-3592.58-1977.25-1977.25-3536.94-2562.22-2785.04-1977.25-1896.23-1799.1-1665.363586-35861733.33-1733.333705.5119781744.111744.113928.411680.881854.952256.81931.613208.69-1665.36-3705.51-1978-1744.11-1744.11-3928.41-1680.88-1854.95-2256.8-1931.61-3208.691813.452061.741220.683740.884103.666968.522261.362261.364103.661745.432261.364103.66-1813.45-2061.74-1220.68-3740.88-4103.66-6968.52-2261.36-2261.36-4103.66-1745.43-2261.36-4103.662272.12' of type 'string'
    at g (app://./js/chunk-vendors.55ed8978.js:344:43422)
    at m (app://./js/chunk-vendors.55ed8978.js:344:43006)
    at B.I (app://./js/chunk-vendors.55ed8978.js:344:47489)
    at B.set value [as value] (app://./js/chunk-vendors.55ed8978.js:344:45691)
    at new B (app://./js/chunk-vendors.55ed8978.js:344:44668)
    at new ne (app://./js/chunk-vendors.55ed8978.js:344:48562)
    at oe (app://./js/chunk-vendors.55ed8978.js:344:52462)
    at Ae.pesa (app://./js/chunk-vendors.55ed8978.js:344:52520)
    at p (app://./js/index.ab8ed1e6.js:1:95303)
    at Function.toDocValue (app://./js/index.ab8ed1e6.js:1:94341)
```

**Version**: `0.7.0`
**Platform**: `win32`
**Path**: `/edit/SalesInvoice/SINV-1085`
**Language**: `undefined`
**Country**: `in`

**Comment by 18alantom** [comment]
Hey, thanks for raising the issue. If you don't mind, could you share your database, it would help debug this issue, you can DM it to me on telegram [@nalamot](https://t.me/nalamot).


I think jumping versions from `0.4.2-beta` to `0.6.5` may have caused the database to get corrupted. As you mentioned, there have been several large database changes since then.

**Comment by raul-castillo** [comment]
Hey, Alan! Thank you so much for your quick reply!

Absolutely, I will send you my database right now.

Thanks again for looking into this!

**Comment by 18alantom** [comment]
Fixed this issue in https://github.com/frappe/books/pull/495 will release a version with the bug fix soon.
