### ISSUE TITLE
Date rendering issue

### ISSUE THREAD

**Issue by raul-castillo** [frappe/books#497]
I have noticed that when I set a date for an invoice, it always shifts back by one day.

This seems to be a 'rendering' issue, since if I go check the entry with a database viewer, the database has the correct date registered, but back in the GUI of the app (or even if I try to print to PDF), the dates in documents always appear one day behind.

![image](https://user-images.githubusercontent.com/67699453/203802350-2da1c2f7-dbf9-4ed3-a870-442b3956b0bd.png)

![image](https://user-images.githubusercontent.com/67699453/203802649-41a08df8-566e-4285-a87e-c161c68a2f49.png)

**Comment by 18alantom** [comment]
@raul-castillo hey, on what version are you facing this issue?

**Comment by 18alantom** [comment]
Doesn't seem to be there in the latest version, hence closing (let me know if you're still facing it).
