### ISSUE TITLE
Cannot find inventory check box.

### ISSUE THREAD

**Issue by Nofal-Mami** [frappe/books#499]
<h2>Description</h2>
Cannot find inventory check box.

**Version**: `0.7.1`
**Platform**: `win32`
**Path**: `/settings`
**Language**: `undefined`
**Country**: `tn`

**Comment by 18alantom** [comment]
Hey, inventory just got completed. No version has been released yet. It will be in the next few days.

**Comment by 18alantom** [comment]
Here's the release: https://github.com/frappe/books/releases/tag/v0.8.0-beta.0

**Comment by Nofal-Mami** [comment]
Hi,
How to do upgrade please
