### ISSUE TITLE
Refresh Button to Reload Database

### ISSUE THREAD

**Issue by GoutamHebbar** [frappe/books#505]
_If I deleted some accounts, it is still being shown in list of accounts but when I click on it I get some error.._ 

I suggest that a **refresh button** should be added so as to **reload the database without closing and reopening Books**

**Comment by 18alantom** [comment]
I've fixed that account reloads issue. Let me know if you face a similar issue. Ideally, the software should be able to reload without the user having to press a reload button.

Btw, you can reload the app without closing and reopening using `Ctrl + R` or `command + R` (the browser refresh shortcut).

**Comment by GoutamHebbar** [comment]
Thanks. I didn't knew about that shortcut. It will be surely be useful to me.
