### ISSUE TITLE
How to do upgrade

### ISSUE THREAD

**Issue by Nofal-Mami** [frappe/books#508]
<h2>Description</h2>
Hi,
Need steps to do upgrade to latest version, could you share steps please.

**Version**: `0.7.1`
**Platform**: `win32`
**Path**: `/get-started`
**Language**: `undefined`
**Country**: `tn`

**Comment by 18alantom** [comment]
Hey, it should be upgrading on its own, here is what happens
1. It detects the new version and downloads it.
2. On restart new version is installed.

If the above process is not taking place for you then do the following:
1. Uninstall the previously installed version (do not remove the `.db` file).
2. Download the installer from the [download page](https://frappebooks.com/download).
3. Install the new version and open it.
4. If it doesn't open your db file then click on Existing File ([ref](https://docs.frappebooks.com/setting-up/getting-started.html))
