### ISSUE TITLE
Cannot download new updates

### ISSUE THREAD

**Issue by Nofal-Mami** [frappe/books#511]
<h2>Description</h2>
Cannot downloads new updates, I am getting below error message, any idea?

<h2>Error Info</h2>

**Error**: _Error: Cannot download "https://github.com/frappe/books/releases/download/v0.8.0-beta.0/Frappe-Books-Setup-0.8.0-beta.0.exe", status 404: Not Found_

**Stack**:
```
Error: Cannot download "https://github.com/frappe/books/releases/download/v0.8.0-beta.0/Frappe-Books-Setup-0.8.0-beta.0.exe", status 404: Not Found
    at ClientRequest.<anonymous> (C:\D\FrappeBooks\Frappe Books\resources\app.asar\background.js:2:414570)
    at ClientRequest.emit (node:events:390:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:6917)
    at SimpleURLLoaderWrapper.emit (node:events:390:28)
```

**Version**: `0.7.1`
**Platform**: `win32`
**Path**: `/get-started`
**Language**: `undefined`
**Country**: `tn`

**Comment by 18alantom** [comment]
I'll take a look, meanwhile you can download it from here: https://github.com/frappe/books/releases/tag/v0.8.0-beta.0

**Comment by 18alantom** [comment]
It should work now, it was a link naming issue.
