### ISSUE TITLE
New locale and date format (Switzerland)

### ISSUE THREAD

**Issue by manuGe** [frappe/books#514]
I noticed that under Setup -> Settings -> System the locale "Switzerland (de-CH)" is missing. There is only the locale "Switzerland (fr-CH)". Since there are several languages spoken in Switzerland, it might make sense to add this locale. However, German (de) is the most widely spoken language.

Concerning the date format it would make sense to add the format 
Day.Month.Year (DD.MM.YYYY), because this is the usual format in Switzerland.

**Comment by 18alantom** [comment]
Updated both https://github.com/frappe/books/commit/80520961a5eeaa91aa4791a145992ec34f2a159e

W.r.t locale: changed the default locale of Switzerland to `"de-CH"`, custom locales can be entered so `"fr-CH"` can be entered manually.
