### ISSUE TITLE
Details required in Invoice

### ISSUE THREAD

**Issue by bpminfotech** [frappe/books#515]
1. Customer full address not displaying in invoice
2. Item Description nnot displaying in invoice.
3. Bank account full details not displaying, infact there is no option to capture complete bank account details..

**Comment by 18alantom** [comment]
@bpminfotech What are the bank account details you would like to show?

**Comment by bpminfotech** [comment]
Hi there, Normally in Invoice we need to show Bank account name, number
and IFS Code . There was option of single text field to enter bank account
name but its not coming in pdf invoice.

Thanks a lot..
Regards,
Nagendra

**Comment by 18alantom** [comment]
In the next version of Frappe Books the Template Builder will be included.

Once it's out, you should be able to duplicate one of the existing templates and add whatever details you'd like to it to create a custom template.
