### ISSUE TITLE
Save button is not appearing

### ISSUE THREAD

**Issue by bpminfotech** [frappe/books#517]
Hi, If we edit existing, purchase items  record, SAVE button is not appearing.

**Comment by bpminfotech** [comment]
Even,  in Sales Items also, NO Save button, if we edit existing record.

**Comment by 18alantom** [comment]
fixed it here: https://github.com/frappe/books/commit/0e0c8a001ad6b23bbc18145b98dd62b159181563

**Comment by bpminfotech** [comment]
highly appreciated, I will check this.. Thanks
