### ISSUE TITLE
Point of sale module (POS)

### ISSUE THREAD

**Issue by MCasperF** [frappe/books#538]
Can the team work on a module for pos that use Touch screen and barcode reader together

**Comment by 18alantom** [comment]
A version with a Barcode component will be released soon. POS is a work in progress.

**Comment by Sunitsarode** [comment]
Hi
Please update with POS and Fiscal Year setup. The software totally incomplete without this.

**Comment by Isaac-GC** [comment]
The POS feature was released in v0.20.0 of FrappeBooks

Closing this issue.

**Comment by Sunitsarode** [comment]
Thanks for providing POS facility to Frappe Books
