### ISSUE TITLE
bug: getStockQuantity date filters not working

### ISSUE THREAD

**Issue by akshayitzme** [frappe/books#540]
<h2>Description</h2>

![image](https://user-images.githubusercontent.com/60477442/216345007-2128ebf0-df09-4deb-954a-0209cba1ce69.png)

the date filters in the `getStockQuantity`  function defined in the `backend/database/bespoke.ts` not working.

therefore the `Opening Quantity`  is giving zero value.

is it because an SQL function (date) exists with the same name of the field `date` in the `StockLedgerEntry` table ?

<h2>Error Info</h2>

**Error**: 

**Version**: `0.8.0`
**Platform**: `linux`
**Path**: `/`
**Language**: `undefined`
**Country**: `in`

**Comment by 18alantom** [comment]
The field does work as expected but compares `datetime` values.

For the opening balance to be positive the entries have to have been made before the date range.

**The function you mentioned is not used to calculate the Stock Balance.**
