### ISSUE TITLE
Item Created from purchase bill does not show up in items list

### ISSUE THREAD

**Issue by parajulizRoman** [frappe/books#544]
![Screen Shot 2023-02-03 at 16 12 57](https://user-images.githubusercontent.com/16022010/216578844-484734d2-6995-4c0c-9d2d-9f654af22049.png) : Purchase Invoice.
![Screen Shot 2023-02-03 at 16 13 18](https://user-images.githubusercontent.com/16022010/216579082-e81d1898-12c4-46a0-9bbe-c997bf19b669.png) : Items created not shown in item list
![Screen Shot 2023-02-03 at 16 15 26](https://user-images.githubusercontent.com/16022010/216579151-9ad6aaa4-412d-4876-a9dd-1da650d160a6.png) : it is shown in purchased item list
Moreover, items once purchased are not editable : no space for correction

**Comment by Ayuen-madyt** [comment]
Purchase items is different from common items. unless you mark the item as for both in this case (both sales item and purchase items) it will only appear on purchased items or sales item

**Comment by 18alantom** [comment]
Editing of Item names isn't supported yet due to a few reasons.

As for common Items appearing not appearing in a specific list, the reasoning given by @Ayuen-madyt is apt.
