### ISSUE TITLE
Invoice language

### ISSUE THREAD

**Issue by wouter-deen** [frappe/books#561]
I hate to have software in my own language, but it would be nice to have the option to customize the language of invoices. For example, I sell services to Dutch customers and my software is in English, and I'd like to have the field labels on the invoice in Dutch.

**Comment by 18alantom** [comment]
You can change the language of the app from the DB Selection screen. After this when you check the Print View, the labels should be in the selected language.

We have Dutch translations, but if you find that some of the labels haven't been translated then it's cause the translations haven't been updated.

On cross-checking the Print template code, several of the labels have not been marked for translation, will close this once I've updated those.

**Comment by 18alantom** [comment]
The labels have now been marked for translation.
