### ISSUE TITLE
When the To Date value is changed, no values are displayed. 

### ISSUE THREAD

**Issue by smalldale** [frappe/books#565]
<h2>When the To Date value is changed, no values are displayed. </h2>

![image](https://user-images.githubusercontent.com/49019693/222058954-9307d39b-98ed-4860-9b8e-27807d683cd0.png)

How to replicate:
1. Create a demo
2. Navigate to "Report".
3. Change the value of the "Date or To Date" filter.

It happen in version 0.9 and 0.8, but it's normal in 0.7.1

**Version**: `0.9.0` `0.8.0`
**Platform**: `win32`
**Path**: `/report/BalanceSheet`

**Comment by 18alantom** [comment]
Fixed: https://github.com/frappe/books/commit/c6ca4f4e4c6d51ff590c3208943a7bb6d8ea1906 should be out in the next release
