### ISSUE TITLE
Add number series in the search function

### ISSUE THREAD

**Issue by Ramchandra98** [frappe/books#588]
<h2>Description</h2>
Add number series in the search function

<h2>Steps to Reproduce</h2>
 Search for number series after pressing Crtl+k

![image](https://user-images.githubusercontent.com/65016843/229368024-62708ac4-69b1-4879-acba-0b61a6cdad38.png)

<h2>Info</h2>

**Version**: `0.11.0`
**Platform**: `win32`
**Path**: `/chart-of-accounts`
**Language**: `undefined`
**Country**: `in`

**Comment by 18alantom** [comment]
fix will be in the next release: https://github.com/frappe/books/pull/587/commits/a32cb503e1f06fce8d64b896fd4be89b51f0f7db
