### ISSUE TITLE
Unable to Create new number series

### ISSUE THREAD

**Issue by Ramchandra98** [frappe/books#589]
<h2>Description</h2>
I wanted to have different number series for new years hence wanted to create new ones but I am unable to select reference type i.e which type of voucher I want to make

<h2>Steps to Reproduce</h2>
1. Open the Number series menu 
2. Click on Reference Type
3. There will be no response from the software allowing to select which type we want to create

https://user-images.githubusercontent.com/65016843/229368569-80428ccf-0d5d-4c5d-8a77-dac8086dca13.mp4

<h2>Info</h2>

**Version**: `0.11.0`
**Platform**: `win32`
**Path**: `/list/NumberSeries/Number Series?edit=1

**Comment by 18alantom** [comment]
fix will be in the next release: https://github.com/frappe/books/pull/587/commits/a32cb503e1f06fce8d64b896fd4be89b51f0f7db
