### ISSUE TITLE
Clicking on an item in the list panel does not show the item details

### ISSUE THREAD

**Issue by africlouds** [frappe/books#59]
When you click on a list item in the central panel, it is expected to see its details in the main details section. However,  this is not the case when you click on top of the text, it requires clicking a bit to the right outside the text. It happens for all sections party, invoice, item, etc

Using Chrome Version 67.0.3396.99 (Official Build) (64-bit) on Ubuntu

**Comment by sahil28297** [comment]
This issue has been resolved
