### ISSUE TITLE
oversell prevent and different cost and sell price for products 

### ISSUE THREAD

**Issue by avvvar** [frappe/books#590]
Hi,

I am facing two issues here

1- is there any way to prevent sales of more than the available quantity in stock?
2-why there is not sales price and cost price? how can I define an item for both sales and purchase but set the sales price higher than the cost price

**Comment by pranimation** [comment]
IMO not having cost price and sales price is a bug, in "item" if we want to add item for "both" you don't have option to define both prices. so for reselling a product this make a hurdle. to get around we generally put different name for same product having purchase and sales item separated.

**Comment by 18alantom** [comment]
Latest version has [Price Lists](https://docs.frappebooks.com/entries/price-list.html) added. Hence, Closing this.
