### ISSUE TITLE
Duplicate values while exporting CSV of Sales invoice filtered by 'Party'

### ISSUE THREAD

**Issue by pranimation** [frappe/books#596]
<h2>Description</h2>
Duplicate values while exporting CSV of Sales invoice filtered by 'Date'

<h2>Steps to Reproduce</h2>
Create filter by party name, you will see x rows of data, but exporting that as csv will have 2x data.

<h2>Info</h2>

**Version**: `0.12.0`
**Platform**: `linux`
**Path**: `/list/SalesInvoice`
**Language**: `undefined`
**Country**: `in`

**Comment by 18alantom** [comment]
This is not an error, the rows are duplicate because of the tables present in invoices (`SalesInvoiceItem` and `TaxSummary`).

This is required because you can't nest data in the `csv` format. You can do this using `json`.
