### ISSUE TITLE
sales invoice not being displayed

### ISSUE THREAD

**Issue by meet984** [frappe/books#606]
<h2>Description</h2>
when clicking on sales entry it shoes blank no sales invice or details just black space

<h2>Steps to Reproduce</h2>
Add steps to reproduce the error...

<h2>Info</h2>

**Version**: `0.13.0`
**Platform**: `win32`
**Path**: `/edit/SalesInvoice//22-233`
**Language**: `English`
**Country**: `in`
![frappe book](https://user-images.githubusercontent.com/101857011/234211727-a8f66394-c8d8-4d0a-b598-dcb64d41ba8c.png)

**Comment by 18alantom** [comment]
For future reference, I debugged the issue with the db in which it occurred. Issue is because `"/"` values in the Number Series was throwing off navigation.
