### ISSUE TITLE
Cannot create address on Customer

### ISSUE THREAD

**Issue by JeffArwady** [frappe/books#607]
<h2>Description</h2>
When creating a customer, I am unable to create an address; both during customer creation and after I save the customer.

<h2>Steps to Reproduce</h2>
Create a customer without an address
Navigate to the above customer
Click the Address field
Click the "Create" button/link
NOTHING HAPPENS

<h2>Info</h2>

**Version**: `0.13.0`
**Platform**: `darwin`
**Path**: `/edit/Party/Jeff Edward Customer`
**Language**: `undefined`
**Country**: `us`

**Comment by JeffArwady** [comment]
Looks like the intent is that you type the name of the address in the address field and then it works.  Closing my issue.

**Comment by 18alantom** [comment]
Reopening cause unexpected UX. Clicking Create should open the Quick Edit form for Address (even if no value).
