### ISSUE TITLE
After install on mac unable to open application

### ISSUE THREAD

**Issue by amet123** [frappe/books#61]
“Frappe Accounting” can’t be opened because it is from an unidentified developer.

Your security preferences allow installation of only apps from the App Store and identified developers.

“Frappe Accounting” is on the disk image “Frappe.Accounting-0.0.2.dmg”. Chrome downloaded this disk image today at 11:04 AM from github.com.

**Comment by netchampfaris** [comment]
This distribution is still unsigned. To open it you can right click -> Open.

**Comment by willywax** [comment]
install yarn
run command yarn in the project folder 
run yarn run  
then choose choose start or type start
