### ISSUE TITLE
Workflow of shpt & receipt

### ISSUE THREAD

**Issue by promexio** [frappe/books#610]
Hi, 
I have the. following issue: 
A Sales Invoice can be selected to be shipped. 
Though, it should be the other way around: select a shpt to create the invoice. 
Can you please implement this to future versions.

Gabriel

**Comment by promexio** [comment]
Any news for this issue? 
The current workflow is not correct! 
---If you ship *after* you invoiced the revenue defers from the performance (performance obligation): you have to post it on another account of the balance sheet not p&l.

**Comment by 18alantom** [comment]
@promexio I have been busy with a side task, once that is done I'll get back to this. Will try and push it within the next two releases.

> The current workflow is not correct!

This has been asked for by a couple of users, although I do agree that it should be allowed the other way round too.
