### ISSUE TITLE
CoA Error

### ISSUE THREAD

**Issue by chalis11** [frappe/books#641]
<h2>Description</h2>
Chart of Account Can't be edited after create

<h2>Steps to Reproduce</h2>
Add steps to reproduce the error...

<h2>Info</h2>

**Version**: `0.14.1`
**Platform**: `darwin`
**Path**: `/chart-of-accounts?edit=1

**Comment by 18alantom** [comment]
You can delete and add accounts: [documentation](https://docs.frappebooks.com/miscellaneous/chart-of-accounts.html)
If the account was used for a transaction then you cannot use it.
