### ISSUE TITLE
Repost for backdated entries

### ISSUE THREAD

**Issue by AhmadAzm** [frappe/books#662]
I apologize I have not tested this feature and I am uncertain if it is automated in this app. However, it is a crucial aspect. In situations where I sell an item without knowing its actual cost, I require the ability to modify the price in the purchase invoice after making sales from the item. This will alter the cost of goods sold in subsequent sales transactions. Such scenarios occur frequently, whether due to landed cost or other reasons for changing the initial purchase invoice amount such as a later discount from supplier

**Comment by 18alantom** [comment]
@AhmadAzm you can use use the **Save → Submit** workflow to your advantage in this case. When you **Save** the Invoice, accounting entries are not created. They are created only when you **Submit**.

You can **Submit** the Invoice when you are certain of the price of the Item. When an Invoice has not been **Submitted** you can still edit the values.

If this doesn't fit your use case do let me know as to why it does not.

**Comment by 18alantom** [comment]
closing cause no reply
