### ISSUE TITLE
Adding New Translation

### ISSUE THREAD

**Issue by iamMHZ** [frappe/books#664]
I would like to add a new language. Is adding the new x.csv file to the trasnlation directory all I have to do ? 
It would be my first PR to the repo, I would be pleased to know any pipeline that you have for accepting PRs.

**Comment by 18alantom** [comment]
@iamMHZ yup that's pretty much it. The initial template `language.csv` file is generated by using a command, here's the [reference](https://github.com/frappe/books/wiki/Contributing-Translations#generating-the-language-file). 

Do go through the above link once, if you need any clarification do let me know.

**Comment by iamMHZ** [comment]
@18alantom 
Thank you for your response.
