### ISSUE TITLE
Problem with date in sales invoice

### ISSUE THREAD

**Issue by Uocharles** [frappe/books#677]
<h2>Description</h2>
Add some description... I have found an annoying thing with the date in the sales invoice section not holding to the selected date when a new entry is made, and date can not be changed after submission and entry can not be removed after submission.

<h2>Steps to Reproduce</h2>
Add steps to reproduce the error... Make a new entry in sales invoices fill out form then select date and save, Saving drops the date back one day and if you did not see it when submitting creates another entry with the same date as your pervious entry. To reproduce this you may need to create a second entry so the 2nd entry can drop back to the first entries date. There should be a way to remove or fix fields after submission. 

<h2>Info</h2>

**Version**: `0.16.0`
**Platform**: `win32`
**Path**: `/edit/SalesInvoice/SINV-1012`
**Language**: `undefined`
**Country**: `us`

**Comment by 18alantom** [comment]
Should be fixed in the next release.

I've switched the date and date time fields from custom components to use the native ones, so should be bug free.

**Comment by 18alantom** [comment]
Closing cause it should be fixed in [0.17.0](https://github.com/frappe/books/releases/tag/v0.17.0), feel free to reply if it still persists.
