### ISSUE TITLE
[Suggestion] Add CLI Usage

### ISSUE THREAD

**Issue by ilovefreesw** [frappe/books#681]
Would be nice to manage invoices and print them using Frappe Books from CLI. Can also be helpful in generating bulk invoices or calling from other programs or scripts.

**Comment by 18alantom** [comment]
Closing this cause seems like an extremely niche use case.

Bulk entries can be created using the [Importer Wizard](https://docs.frappebooks.com/miscellaneous/import-wizard.html) (which can be used without external files).

As for calling from other programs, exact requirement is not clear.
