### ISSUE TITLE
Journal Entry - New Entry - Date Selector Changes After Selection

### ISSUE THREAD

**Issue by the-narwhal** [frappe/books#689]
<h2>Description</h2>
Journal entry date selector overrides user selected date with the date prior to selection. E.g. July 10, 2023 selected by user, field updates to July 9, 2023 once clicking out of the field.

<h2>Steps to Reproduce</h2>

1. Common>Journal Entry>New Entry
2. Pick date
3. Click outside of date field
4. Review date field

<h2>Info</h2>

**Version**: `0.17.0`
**Platform**: `darwin`
**Path**: `/edit/JournalEntry/New Journal Entry 01`
**Language**: `-`
**Country**: `us`

**Comment by the-narwhal** [comment]
@18alantom, while trying to find the root cause the following console outputs occurs. It appears the Date() function is messing up the local timezone potentially.


File: /books/src/components/Controls/Date.vue

console.logs:
      console.log('target.value:', target.value);
      let value: Date | null = new Date(target.value);
      console.log('value:', value);
      value.setHours(0, 0, 0, 0);

UI Date Picked: Jul 18 2023

Output:
Date.vue:117 target.value: 2023-07-18
Date.vue:119 value: Mon Jul 17 2023 20:00:00 GMT-0400 (Eastern Daylight Time)

**Comment by 18alantom** [comment]
Thanks for pointing it out @01111010t should be fixed in #699 

It'll be out in the next release, if you still find that there are date issues feel free to open a new issue.
