### ISSUE TITLE
Date.vue Handles Local Time Incorrectly

### ISSUE THREAD

**Issue by the-narwhal** [frappe/books#700]
I grabbed the latest master with #699 , issue still persists with the Journal Entry page.

I was able to build on your fix to resolve it in date.vue line 118:
      //let value: Date | null = new Date(target.value);
      let value: Date | null = DateTime.fromISO(target.value).toJSDate();

Maybe this will help close it out?

**Comment by 18alantom** [comment]
Thanks once again, I've pushed the fix in #703  switched the usage for when the value is pulled out of the DB too.
