### ISSUE TITLE
why It has no  p&L ledger 

### ISSUE THREAD

**Issue by Ap7737** [frappe/books#714]
<h2>Description</h2>
Add some description...

<h2>Steps to Reproduce</h2>
Add steps to reproduce the error...

<h2>Info</h2>

**Version**: `0.18.0`
**Platform**: `win32`
**Path**: `/report/BalanceSheet`
**Language**: `-`
**Country**: `in`

**Comment by 18alantom** [comment]
Do you mean the Profit and Loss report? This does exist ([docs](https://docs.frappebooks.com/analytics/profit-and-loss.html)).

**Comment by 18alantom** [comment]
Closing this as vague description and no reply.
