### ISSUE TITLE
Accounting Entry Issue at Shipping Document

### ISSUE THREAD

**Issue by aheer7** [frappe/books#716]
<h2>Wrong accounting entry at shipment document</h2>
Currently accounting entry hit the ledgers with selling rate whether it should be based on valuation rate. Following Double entry is being posted with selling price
Dr. Cost of Goods Sold
Cr. Stock in hand
Due to which individual account ledgers and ultimately P&L statement is being disturbed.
Kindly resolve ASAP
<h2>Steps to Reproduce</h2>

- Add a new item
- Add Purchase invoice, purchase receipt and payment with unit cost of 50 Rupees and 10 quantity
- Add sales invoice, shipping and payment with unit price of 100 Rupees and quantity 10
- All other impacts on stock and accounting entries are perfect except shipping entry 
- At shipping Stock in hand and Cost of Goods Sold should be booked at valuation rate of 50. But it is reflecting on sales rate which is wrong

<h2>Info</h2>

**Version**: `0.18.0`
**Platform**: `darwin`
**Path**: `/get-started`
**Language**: `-`
**Country**: `ca`

**Comment by aakvatech** [comment]
This bug essentially discourages use of Inventory
