### ISSUE TITLE
Not able to add salary to the account section

### ISSUE THREAD

**Issue by njmulsqb** [frappe/books#731]
Hi,

I am trying to add Salary to the account section while adding purchase payments, but it is showing me error
![image](https://github.com/frappe/books/assets/47940898/2de8041c-9107-4149-848f-0b1de3637d0e)
![image](https://github.com/frappe/books/assets/47940898/84a9e584-3664-4e71-82f0-1a347ebaad16)

**Comment by 18alantom** [comment]
![Screenshot 2023-09-12 at 15 13 44](https://github.com/frappe/books/assets/29507195/e645bb15-dcfa-46f5-89a4-9affacd32b30)

@njmulsqb this is cause Salary is a default account that already exists under Indirect Expenses.

If you want to add the Salary account, I'd suggest using a [Journal Entry](https://docs.frappebooks.com/transactions/journal-entries.html).


Closing this, as it's working as expected, if you have a doubt regarding this feel free to respond here or create a new issue.

**Comment by 18alantom** [comment]
Discussion that refers to this: https://github.com/frappe/books/discussions/730
