### ISSUE TITLE
adding items in invoice

### ISSUE THREAD

**Issue by pixelspro** [frappe/books#745]
<h2>Description</h2>
Add some description...

<h2>Steps to Reproduce</h2>
Add steps to reproduce the error...

<h2>Info</h2>

**Version**: `0.18.0`
**Platform**: `win32`
**Path**: `/edit/SalesInvoice/New%20Sales%20Invoice%2002`
**Language**: `-`
**Country**: `in`

**Comment by 18alantom** [comment]
Closing cause duplicate of #746
