### ISSUE TITLE
feat: allow multiple selection of the same item

### ISSUE THREAD

**Issue by pixelspro** [frappe/books#746]
<h2>Description</h2>
Add some description...

<h2>Steps to Reproduce</h2>
Add steps to reproduce the error...

<h2>Info</h2>

**Version**: `0.18.0`
**Platform**: `win32`
**Path**: `/edit/SalesInvoice/New%20Sales%20Invoice%2002`
**Language**: `-`
**Country**: `in`

**Comment by 18alantom** [comment]
This has been fixed in develop, will be out in the next version.

**Comment by pixelspro** [comment]
Also, in the above case, keep the "Item Description" textbox editable in sales invoice. This will help to add a small comment for each item when i add same item multiple times in a invoice.

**Comment by pixelspro** [comment]
Hi, Thanks for this update. I can now change the description of each line item. But the description does not show up when I print the invoice. I want the description of each line item visible when I take a print. Please help with this feature update.
