### ISSUE TITLE
No wizard after installation of Beta 0.0.2 on Windows

### ISSUE THREAD

**Issue by ivangretsky** [frappe/books#76]
Good day!

I downloaded a Windows installer from [here ](https://github.com/frappe/accounting/releases)and ran it. After the installation the app window opens, but it is blank, no wizard is starting up. I do not see a way to start a wizard from the menu either. Am I missing something?

**Comment by ivangretsky** [comment]
Is it fixed? Or irrelevant?

**Comment by rmehta** [comment]
It's fixed. Get the latest beta via https://frappebooks.com <https://frappebooks.com/>

**Comment by ivangretsky** [comment]
Thanks!
