### ISSUE TITLE
Question: Intergration

### ISSUE THREAD

**Issue by jj10133** [frappe/books#762]
Hi everyone, I never heard about this product this is great.. I'm currently seeking to add sales automatically into books. Is there anyway how I can add it. Like every sale on my site makes an entry to books?

**Comment by akshayitzme** [comment]
> Hi everyone, I never heard about this product this is great.. I'm currently seeking to add sales automatically into books. Is there anyway how I can add it. Like every sale on my site makes an entry to books?

Hi @warmachinesocial,
As of now, Frappe Books runs completely offline. It doesn't have the feature you mentioned. Maybe you can use [Import Wizard](https://docs.frappebooks.com/miscellaneous/import-wizard.html) to Import Data into Frappe Books.
