### ISSUE TITLE
How to find the link of database file for backup purpose?

### ISSUE THREAD

**Issue by Gaurangb9** [frappe/books#764]
<h2>Description</h2>
I can't find the db path in FB, I need to take regular backup

<h2>Steps to Reproduce</h2>
N.A.

<h2>Info</h2>

**Version**: `0.19.0`
**Platform**: `win32`
**Path**: `/chart-of-accounts`
**Language**: `English`
**Country**: `in`

**Comment by akshayitzme** [comment]
Hi @Gaurangb9 ,

I assume you're running FB on Windows. In Windows, the databases are usually stored under the `Documents/Frappe Books` directory.

Other than this there are a couple of hacky ways to find where the DB's are located.

1. DB location is displayed on FB's Title Bar (works on Windows 11)
![image](https://github.com/frappe/books/assets/60477442/3150e75e-f66f-4432-811f-c08be930205f)

2. DB Location is displayed on the Change DB 
  ![image](https://github.com/frappe/books/assets/60477442/87fa35bb-de2d-415f-bc2b-c74f01b5d700)<br>
  Click on Change DB and it opens up a page that displays all of the databases Frappe Books has worked with.<br/>
  ![image](https://github.com/frappe/books/assets/60477442/29ac55bb-0497-4497-9680-55d9d936b20f)

I hope this helps.

**Comment by Isaac-GC** [comment]
Hi @Gaurangb9,

Do you still need help with this issue?
