### ISSUE TITLE
Error: Could not locate the bindings file

### ISSUE THREAD

**Issue by sahalatq** [frappe/books#767]
<h2>Description</h2>
Add some description...

<h2>Steps to Reproduce</h2>
Add steps to reproduce the error...

<h2>Info</h2>

**Error**: _DatabaseError: Error
Could not locate the bindings file. Tried:
 → /Users/abdallahalnsour/Desktop/Developer/books/node_modules/better-sqlite3/build/better_sqlite3.node
 → /Users/abdallahalnsour/Desktop/Developer/books/node_modules/better-sqlite3/build/Debug/better_sqlite3.node
 → /Users/abdallahalnsour/Desktop/Developer/books/node_modules/better-sqlite3/build/Release/better_sqlite3.node
 → /Users/abdallahalnsour/Desktop/Developer/books/node_modules/better-sqlite3/out/Debug/better_sqlite3.node
 → /Users/abdallahalnsour/Desktop/Developer/books/node_modules/better-sqlite3/Debug/better_sqlite3.node
 → /Users/abdallahalnsour/Desktop/Developer/books/node_modules/better-sqlite3/out/Release/better_sqlite3.node
 → /Users/abdallahalnsour/Desktop/Developer/books/node_modules/better-sqlite3/Release/better_sqlite3.node
 → /Users/abdallahalnsour/Desktop/Developer/books/node_modules/better-sqlite3/build/default/better_sqlite3.node
 → /Users/abdallahalnsour/Desktop/Developer/books/node_modules/better-sqlite3/compiled/16.13.2/darwin/arm64/better_sqlite3.node
 → /Users/abdallahalnsour/Desktop/Developer/books/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node
 → /Users/abdallahalnsour/Desktop/Developer/books/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node
 → /Users/abdallahalnsour/Desktop/Developer/books/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node
 → /Users/abdallahalnsour/Desktop/Developer/books/node_modules/better-sqlite3/lib/binding/node-v103-darwin-arm64/better_sqlite3.node_

**Stack**:
```
Error: Could not locate the bindings file. Tried:
    at Object.raw (/Users/abdallahalnsour/Desktop/Developer/books/node_modules/knex/lib/knex-builder/make-knex.js:115:30)
    at Function.value (/Users/abdallahalnsour/Desktop/Developer/books/node_modules/knex/lib/knex-builder/make-knex.js:91:29)
    at DatabaseCore.connect (/Users/abdallahalnsour/Desktop/Developer/books/backend/database/core.ts:97:21)
    at DatabaseManager._connect (/Users/abdallahalnsour/Desktop/Developer/books/backend/database/manager.ts:46:19)
    at DatabaseManager.connectToDatabase (/Users/abdallahalnsour/Desktop/Developer/books/backend/database/manager.ts:38:30)
    at DatabaseManager.createNewDatabase (/Users/abdallahalnsour/Desktop/Developer/books/backend/database/manager.ts:34:23)
    at /Users/abdallahalnsour/Desktop/Developer/books/main/registerIpcMainActionListeners.ts:220:16
```

**Version**: `0.19.0`
**Platform**: `darwin`
**Path**: `/`
**Language**: `-`

**Comment by ableksaju** [comment]
@sahalatq Are you still encountering this issue? Could you provide additional details about it?

**Comment by akshayitzme** [comment]
closing this cause of lack of response.
