### ISSUE TITLE
 alter table Payment add column referenceType text not null - Cannot add a NOT NULL column with default value NULL

### ISSUE THREAD

**Issue by AballahNsour** [frappe/books#777]
<h2>Description</h2>
Add some description...

<h2>Steps to Reproduce</h2>
Add steps to reproduce the error...

<h2>Info</h2>

**Error**: _DatabaseError: SqliteError
alter table `Payment` add column `referenceType` text not null - Cannot add a NOT NULL column with default value NULL_

**Stack**:
```
SqliteError: alter table `Payment` add column `referenceType` text not null - Cannot add a NOT NULL column with default value NULL
    at Function.get (/Users/abdallah/Desktop/Developer/Accounting/books/node_modules/knex/lib/knex-builder/make-knex.js:43:26)
    at DatabaseCore.

**Comment by mildred** [comment]
This is from the master branch, caused by #743 

Either stop marking the field as required, and update code to gracefully handle NULL values, or provide a default value, or find a way to migrate the data and programatically provide the value for this field

**Comment by mildred** [comment]
In the meantime use a previous version of Books
