### ISSUE TITLE
better-sqlite3 fails to build

### ISSUE THREAD

**Issue by jkroso** [frappe/books#779]
Updating it from v7 to v9 fixes the build issue but seems to cause a migration issue. Is that why it's pinned to v7?

**Comment by mildred** [comment]
I believe the migration issue is not caused by the update. It would be #777

**Comment by Isaac-GC** [comment]
Better-sqlite3 was updated to `9.2.2` in https://github.com/frappe/books/pull/801  and was seen to build successfully. 

Closing issue for now. If you are still encountering problems with better-sqlite3, please reopen this issue
