### ISSUE TITLE
creating a new company fails if there is a space in the path to the filename

### ISSUE THREAD

**Issue by matlads** [frappe/books#784]
`/Users/martin/Documents/Frappe Books/demo.db` fails but `/Users/martin/Documents/Frappe-Books/demo.db` works

**Comment by akshayitzme** [comment]
> `/Users/martin/Documents/Frappe Books/demo.db` fails but `/Users/martin/Documents/Frappe-Books/demo.db` works

Just to get some additional context, are you running Frappe Books on windows ?

**Comment by mildred** [comment]
Cannot confirm this on Linux

**Comment by matlads** [comment]
I am using `macOS 14.1.1 (23B81)`

**Comment by mildred** [comment]
What exactly is the error?

**Comment by matlads** [comment]
I have a done the test again, and it seems to be OK.

It was an error on my end.
