### ISSUE TITLE
Custom Form fields on printable templates??

### ISSUE THREAD

**Issue by BugsWorld** [frappe/books#786]
I was very excited finding out that Frappe Books has the option to add custom fields but after playing around with that option I'm very sad that it's not showing on the printable invoice for example.

If I add extra fields such as Color, weight etc.. to an Item or Invoice, it should show on the printable template. Are there any plans to allow this? Or will you never have this option. Please let me know because if not, then I'm afraid Frappe is not for me.

**Comment by mildred** [comment]
I added custom fields to SalesInvoice and I can add them to the invoice template without issue.

Example:

- add custom field in SalesInvoice named due_date
- add in the print template `{{new Date(doc.due_date).toLocaleDateString()}}`

**Comment by BugsWorld** [comment]
> I added custom fields to SalesInvoice and I can add them to the invoice template without issue.
> 
> Example:
> 
>     * add custom field in SalesInvoice named due_date
> 
>     * add in the print template `{{new Date(doc.due_date).toLocaleDateString()}}`



Sorry for the late reply, but is it possible to pull information from the custom fields of other form types?
For example, when I add a new item to my inventory, I will enter all the details for it including the custom fields I want. But then, is it possible to create an invoice, select that item, and have it show that item's custom fields on the print template? Because as of now, I have to re-enter my custom fields every time I create an invoice even though the item itself already has all those details.

**Comment by akshayitzme** [comment]
> > I added custom fields to SalesInvoice and I can add them to the invoice template without issue.
> > Example:
> > ```
> > * add custom field in SalesInvoice named due_date
> > 
> > * add in the print template `{{new Date(doc.due_date).toLocaleDateString()}}`
> > ```
> 
> Sorry for the late reply, but is it possible to pull information from the custom fields of other form types? For example, when I add a new item to my inventory, I will enter all the details for it including the custom fields I want. But then, is it possible to create an invoice, select that item, and have it show that item's custom fields on the print template? Because as of now, I have to re-enter my custom fields every time I create an invoice even though the item itself already has all those details.

As of now, it is not possible to achieve the idea you mentioned. It may come up in the future.
