### ISSUE TITLE
How Do I Import My Chart of Accounts (Excel document) in Frappe Books

### ISSUE THREAD

**Issue by jimk100189** [frappe/books#803]
<h2>Description</h2>
How Do I Import My Chart of Accounts (Excel document)

<h2>Steps to Reproduce</h2>
I have an existing Chart of Accounts with Account Numbers in an Excel spreadsheet.
How do I import this into a new Company I've created in Frappe Books?

<h2>Info</h2>

**Version**: `0.19.0`
**Platform**: `win32`
**Path**: `/chart-of-accounts`
**Language**: `-`
**Country**: `us`

**Comment by Isaac-GC** [comment]
Hi @jimk100189!

Try using the documentation found here (With using the "Account" import type): https://docs.frappebooks.com/miscellaneous/import-wizard.html 

For example, if you have the values in the csv:
<img width="478" alt="image" src="https://github.com/frappe/books/assets/1480896/f04728e8-e27d-4514-9836-3a72abd0b901">

It'll look like this in the import wizard (you can also add/edit the values directly in the Frappe Books import wizard interface as well)
<img width="805" alt="image" src="https://github.com/frappe/books/assets/1480896/db6a5c21-aefa-4c23-922f-765bf307b550">

**Comment by akshayitzme** [comment]
@jimk100189 Do you still need help with this issue ?

**Comment by jimk100189** [comment]
Yes

**Comment by akshayitzme** [comment]
have you tried the above steps (https://github.com/frappe/books/issues/803#issuecomment-1916031390) ?

**Comment by akshayitzme** [comment]
Closing this issue due to lack of replies.
