### ISSUE TITLE
Invoice print seems broken after the recent update

### ISSUE THREAD

**Issue by ankitadudakiya** [frappe/books#824]
The print works fine till you save the invoice in Frappe Books, and it looks intact in the system. But as you save it as PDF it seem broken this is how it looks after save to pdf

<img width="812" alt="image" src="https://github.com/frappe/books/assets/106796221/33d2ad1d-8aca-4389-aa30-65553063fb63">

**Version**: `0.21.0`
**Platform**: `darwin`
**Path**: `/print/SalesInvoice/SINV-23241009`
**Language**: `-`
**Country**: `in`

**Comment by Isaac-GC** [comment]
A fix is being worked on here: https://github.com/frappe/books/pull/827

Just waiting on validation prior to a patch update for the bug
