### ISSUE TITLE
🐛 [Bug] - <sales invoice listed shows no information (New Entry) when clicked>

### ISSUE THREAD

**Issue by CornishWoodsman** [frappe/books#828]
### Expected Behavior

Toi show the invoice data

### Current Behavior

Just shows 'New Enrtry' with a blank page. CPU cranks up...

### Steps to Reproduce

Multiple efforts to delete has created a 'ghost' invoice that I can't edit or delete

### FrappeBooks Version

0.21.0

### Path or Feature name

Sales>Sales invoice>'select' invoice.

### Country

UK

### Language

EN

### OS

Linux x86_64

**Comment by mildred** [comment]
Could you attach a screenshoot? Do you have any more information on how to reproduce this issue?

**Comment by CornishWoodsman** [comment]
I resolved this by deleting the entry in the database- it must have been corrupted somehow.
