### ISSUE TITLE
Invoice created from quote is viewed in incorrect state (seem read only with create payment enabled)

### ISSUE THREAD

**Issue by mildred** [frappe/books#834]
### Expected Behavior

- The invoice should be editable
- Creating a payment from the invoice should not be possible, but it should be possible to save or submit the invoice

Workaround:

- go back to the list of invoices and click on the invoice just created

### Current Behavior

- the invoice is not editable
- an option to create a payment is shown

### Steps to Reproduce

1. Create a quote and submit it
2. Create an invoice from the quote
3. You get redirected to the invoice page which is in incorrect state

### FrappeBooks Version

0.21.0

### Path or Feature name

Quote

### Country

FR

### Language

FR

### OS

Linux x86_64

**Comment by akshayitzme** [comment]
closing as it is fixed in #918
