### ISSUE TITLE
💡 [Feature Request] - Darkmode

### ISSUE THREAD

**Issue by Isaac-GC** [frappe/books#835]
### Summary

Allow users to either follow system theme or manually set the mode (light or dark)

### What problem are you trying to solve?

Visual eye-candy and user preference

### Basic Example

N/A

### Drawbacks

N/A

**Comment by akshayitzme** [comment]
added in #873

**Comment by the-narwhal** [comment]
@ableksaju the Project status of this closed PR is 'Planned', but appears it needs to be updated to 'Released'/Completed. Is this something you can assist with?

**Comment by akshayitzme** [comment]
@Isaac-GC, could you grant me Admin permissions for the project? I'm currently unable to update statuses or manage the board.
