### ISSUE TITLE
💡 [Feature Request] - Enter Payment Date When Submitting Invoice

### ISSUE THREAD

**Issue by JustinFowlerArt** [frappe/books#858]
### Summary

Would like to be able to select the date to use when submitting a purchase invoice and creating a payment record. 

### What problem are you trying to solve?

I typically enter most of my bookkeeping 1-2 times per month. This causes all of the payments to be submitted on the same day, rather than the date of the invoice or a chosen date.

### Basic Example

Currently, submitting a purchase invoice while automatically creating the payment record always enters the payment on the day it was submitted. I would like to be able to select the date that I want to use for the payment.

### Drawbacks

Would need a pop up or other method to select the date of the payment to be submitted.

**Comment by Isaac-GC** [comment]
You should already be able to select the purchase invoice date by changing the Date field when creating a Purchase Invoice


<img width="476" alt="image" src="https://github.com/frappe/books/assets/1480896/5e3f5bb8-1de6-4fbf-b7ee-d41d2d65e09b">

And then when you add a Purchase Payment, if you change the Posting Date it should change to the date that the payment was submitted


<img width="868" alt="image" src="https://github.com/frappe/books/assets/1480896/ed7410c2-bf75-493e-b9f4-0bf129a94b69">

**Comment by JustinFowlerArt** [comment]
Thanks for responding. I should have mentioned that this is specifically when using the "Make Payment On Submit" setting for invoices. This creates a payment using the date that you submit the invoice. I will switch to using this method.
