### ISSUE TITLE
💡 [Feature Request] - Option to disable automatic updates

### ISSUE THREAD

**Issue by smalldale** [frappe/books#859]
### Summary

- Please add option to disable or only notify it the update to the user without installing.
- If update happened in portable version, rather than installed it on Windows host, put in on the same directory as the app. (optional)

### What problem are you trying to solve?

![image](https://github.com/frappe/books/assets/49019693/c9c7b210-6961-48d9-923c-4b190cd7bd4e)
I use Frappe Book Portable on Windows, and it's automatically updated by default. It's causing the app to be installed on the PC by default. Sometimes the user is not yet ready to use the newer version.

### Basic Example

Add it to the settings with the option,
- enable auto update
- only notify the new version, not download or install the new update
- disable auto update

### Drawbacks

Maybe the database cannot load properly on the newer version if the user uses a very old version and then jumps straight to the latest version.

**Comment by Isaac-GC** [comment]
Hi @smalldale, there is already a feature request that exists for this and the solution is currently being worked on 

I'm marking this ticket as a duplicate for https://github.com/frappe/books/issues/841
