### ISSUE TITLE
🐛 [General Question] - Date filter in Purchase Invoices

### ISSUE THREAD

**Issue by benhuangbmj** [frappe/books#868]
### Summary

I was trying to filter my invoices by date. For example, I want to list only the invoices before Jan 1, 2024. But I was not able to figure out the proper syntax. Could you please help? Thanks.

**Comment by ableksaju** [comment]
The date format is YYYY-MM-DD

<img width="993" alt="image" src="https://github.com/user-attachments/assets/e53be8fe-f7bb-45dd-9559-cf41aa208d36">
