### ISSUE TITLE
🐛 [General Question] - adding custom field on InvoiceItem and i want only to show on sales invoices  

### ISSUE THREAD

**Issue by xcode-ae** [frappe/books#870]
### Summary

Hello team, 
i have a question regarding adding custom field on "InvoiceItem" called "fieldname": "lowerupper", for showing in sales invoices and it's working fine, but the issue is also showing in purchasing item invoice,
how to hide it and allow only to be showing on sales invoices as the PurchaseInvoiceItem.json is "extends": "InvoiceItem" means all the information getting from the file called InvoiceItem.json 
<img width="352" alt="Screen Shot 2024-03-24 at 8 57 45 PM" src="https://github.com/frappe/books/assets/112379904/4f2ee303-d0c0-4634-a749-03aa8cad8899">

sales invoice which i want  "lowerupper"
<img width="808" alt="Screen Shot 2024-03-24 at 8 58 27 PM" src="https://github.com/frappe/books/assets/112379904/639ce90a-b0aa-4b57-ad58-7387f50681ed">

purchasing invoice i dont want to be showing  "lowerupper"
<img width="819" alt="Screen Shot 2024-03-24 at 8 59 27 PM" src="https://github.com/frappe/books/assets/112379904/2f5c6e35-b399-476e-b651-e0a56bf166ae">

**Comment by akshayitzme** [comment]
@xcode-ae Hi, I suggest adding the Custom Field in the `SalesInvoiceItem` will solve your use case. Since the custom field is added in `SalesInvoiceItem`, the field will not show up in the `PurchaseInvoiceItem`.

**Comment by xcode-ae** [comment]
> @xcode-ae Hi, I suggest adding the Custom Field in the `SalesInvoiceItem` will solve your use case. Since the custom field is added in `SalesInvoiceItem`, the field will not show up in the `PurchaseInvoiceItem`.

thank you very much i have done it
