### ISSUE TITLE
🐛 [Bug] - Bottom bar in Template builder not visible properly

### ISSUE THREAD

**Issue by pu-raihan** [frappe/books#872]
### Expected Behavior

![image](https://github.com/frappe/books/assets/99407382/ac7f1372-dcf3-4dc8-9162-c2f30534b020)
<br>
This is the expected bottombar

### Current Behavior

![Screenshot 2024-03-26 185744](https://github.com/frappe/books/assets/99407382/22603ee1-cb9f-4a44-8b3c-fa8233351526)
I don't know if this is only in my desktop but the bottom bar isn't fully visible. Not even the texts in it aren't visible

### Steps to Reproduce

Go to Setup -> Print Templates -> choose any template<br>
and there you can see a very small portion of bottom bar which is not correctly rendered

### FrappeBooks Version

0.21.2

### Path or Feature name

Template Builder

### Country

India

### Language

English

### OS

Windows 11

**Comment by ableksaju** [comment]
I’ve checked the issue on my device, and the bottom bar in the Template Builder appears to be working correctly. Could you please try checking again?

<img width="946" alt="Screenshot 2024-08-12 at 11 09 05 AM" src="https://github.com/user-attachments/assets/36cafe08-51b1-4c3b-b570-89cd343f4e86">

**Comment by pu-raihan** [comment]
> I’ve checked the issue on my device, and the bottom bar in the Template Builder appears to be working correctly. Could you please try checking again?
> 
> <img width="946" alt="Screenshot 2024-08-12 at 11 09 05 AM" src="https://github.com/user-attachments/assets/36cafe08-51b1-4c3b-b570-89cd343f4e86">
> 

I think it's a problem with dimensions, since it's not scrollable screens with smaller height might not show it properly

**Comment by ableksaju** [comment]
Couldn't reproduce it, tried resizing the window to the smallest. Still able to see the bottom bar with the scrollbar. Could this be an issue with your device's screen resolution?


<img width="1440" alt="image" src="https://github.com/user-attachments/assets/cb706363-641d-419c-b201-ef5ba172f895">

**Comment by pu-raihan** [comment]
> Couldn't reproduce it, tried resizing the window to the smallest. Still able to see the bottom bar with the scrollbar. Could this be an issue with your device's screen resolution?
> 
> <img alt="image" width="1440" src="https://private-user-images.githubusercontent.com/126228406/357282487-cb706363-641d-419c-b201-ef5ba172f895.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNDExNjUsIm5iZiI6MTcyNDA0MDg2NSwicGF0aCI6Ii8xMjYyMjg0MDYvMzU3MjgyNDg3LWNiNzA2MzYzLTY0MWQtNDE5Yy1iMjAxLWVmNWJhMTcyZjg5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQwNDE0MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNWY5N2M3YzQwZmFmN2Y0MGU3ZDdkMGIwMTY3ZDQ2MTUwZjcwNjhkMjBlMTU0NGRmNGY3YzhjMTU4YzI2OGE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ayX2iupiz0EE7aZa3uuA1adGjCIIsx73zyAetHETF00">

From Your screenshot, I guess you're using mac OS. I tried this in lInux also, works just fine. This problem occurs only in windows when I checked. Can you check it on some system with windows if you haven't already. Thanks
