### ISSUE TITLE
purchase payment option not shown

### ISSUE THREAD

**Issue by computescience** [frappe/books#889]
<h2>Description</h2>
The purchase payment option is not shown on the right corner. It only has options: view linked entries, print, toggle, create, view and ...

<h2>Steps to Reproduce</h2>
After restarting the software, and restarting the computer, it persists for all new entries of purchase invoices.

<h2>Info</h2>

**Version**: `0.21.2`
**Platform**: `win32`
**Path**: `/edit/PurchaseInvoice/PINV-1006`
**Language**: `-`
**Country**: `us`

**Comment by ableksaju** [comment]
@computescience Are you still facing this issue?

**Comment by Slzg** [comment]
1) Make sure document status is not SAVED, not PAID... status should be UNPAID
2) in Purchase Invoice, Payment can be found in CREATE button.

**Comment by akshayitzme** [comment]
@computescience Please try the mentioned steps in the latest FBooks version and please reopen if the issue persists.

> 1. Make sure document status is not SAVED, not PAID... status should be UNPAID
> 
>     2. in Purchase Invoice, Payment can be found in CREATE button.
