### ISSUE TITLE
🐛 [General Question] - Eliminate Electron

### ISSUE THREAD

**Issue by patanne** [frappe/books#890]
### Summary

I am not a fan of electron. Never was. Is there a simple way to modify this project, for tweaking and for use, that I can 'git clone' then 'npm run'? I just want a normal server running in the background. This way I can leave it running on one computer in my house.

**Comment by akshayitzme** [comment]
> ### Summary
> 
> I am not a fan of electron. Never was. Is there a simple way to modify this project, for tweaking and for use, that I can 'git clone' then 'npm run'? I just want a normal server running in the background. This way I can leave it running on one computer in my house.

Hi,
First of all, Books is a system software that is installed and operated in ones operating system. It's not cloud based. We could relate its internal working structure to be a client-server model but it doesn't work like the Frappe framework or similar ones. 

To simply use this application, you could download a release from the Releases tab or [click here](https://github.com/frappe/books/releases). 

For Development, you could simply clone this project, run `npm i` then `npm run dev` 

Also, Books doesn't ship any API's out of the box so there is nothing like leaving the server on, pushing the data when needed. Books is accessible only from the UI itself.

About Eliminating Electron, I don't think its an easy task. This project is tightly coupled with Electron.

**Comment by akshayitzme** [comment]
@patanne Do you still need help with this issue ?

**Comment by patanne** [comment]
yes. i will want this to operate as a traditional web site, so i can access from multiple machines. on any given day i operate from a minimum of two machines. on any given week i operate from a minimum of 6 machines. keeping a synchronized copy of data across 6 installations is a nightmare scenario. via mobileOn Aug 12, 2024, at 12:46 AM, Akshay ***@***.***> wrote:﻿
@patanne Do you still need help with this issue ?

**Comment by akshayitzme** [comment]
> yes. i will want this to operate as a traditional web site, so i can access from multiple machines. on any given day i operate from a minimum of two machines. on any given week i operate from a minimum of 6 machines. keeping a synchronized copy of data across 6 installations is a nightmare scenario. via mobileOn Aug 12, 2024, at 12:46 AM, Akshay ***@***.***> wrote:﻿ @patanne Do you still need help with this issue ? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

To achieve the idea you mentioned, you would have to tweak the whole working structure of Books. The efforts will be as much as you're building it from scratch. I believe it doesn't align with this project's future goals.
