### ISSUE TITLE
Where can I find documentation or swagger for the Books API? Does it have a REST API?

### ISSUE THREAD

**Issue by toduyemi** [frappe/books#892]
### Summary

I am seeking to automate some workflows in rapper. I can't find any documentation for developers or even anything pertainng to an API?

**Comment by akshayitzme** [comment]
> ### Summary
> 
> I am seeking to automate some workflows in rapper. I can't find any documentation for developers or even anything pertainng to an API?

No FBooks doesn't ship REST APIs nor expose any functions for other applications to interact with it. You might have to code that functionality. 

Maybe the following resources could help
1. [Electron Inter-Process Communication](https://www.electronjs.org/docs/latest/tutorial/ipc)
2. [registerIpcMainActionListeners.ts](https://github.com/frappe/books/blob/1e09f5c3df8092fc603a106caa64bddcb20449ff/main/registerIpcMainActionListeners.ts)
3. [main/contactMothership.ts](https://github.com/frappe/books/blob/1e09f5c3df8092fc603a106caa64bddcb20449ff/main/contactMothership.ts#L49-L60)
