### ISSUE TITLE
FRAPPEBOOKS ONLINE VERSION

### ISSUE THREAD

**Issue by builtlikeageek** [frappe/books#896]
### Summary

I'm a Accounting Agency owner and I use frappebooks to manage my business accounts 

I want to host frappebooks as a website and use it online and access it from anywhere in the world.

And as I have expanded my team and they all have good grip on using frappebooks, I do not want to switch to a paid software to be able to use online version.

Please explain to me methods that could be used to host this app online.

**Comment by premdasvm** [comment]
I'm not sure if you can move Frappe Book to the cloud as it is, one thing you could modify the code to use an SQLite hosted in the cloud, and then your team can install the Frappe Book app and connect to the common SQLite DB. Try using something like [Turso — SQLite for Production](https://turso.tech/). This is just my assumption I haven't used Frappe Book that much.

**Comment by ankush** [comment]
https://erpnext.com/ is full-fledged ERP that you're looking for. 

Frappe Books was not designed for online use like this.
