### ISSUE TITLE
🐛 [Bug]  BUILD FAILED - if i run exe file, Not showing anything after yarn build (windows)

### ISSUE THREAD

**Issue by usmanalichohan** [frappe/books#898]
### FrappeBooks Version

Latest

### Path or Feature name

Yarn build

### Country

ID

### Language

English 

### OS

Windows 11

**Comment by ableksaju** [comment]
@usmanalichohan Could you please give the steps to reproduce?

**Comment by akshayitzme** [comment]
closing this cause of lack of response.
