### ISSUE TITLE
Inventory does not work.

### ISSUE THREAD

**Issue by Zagoro** [frappe/books#899]
<h2>Description</h2>
Hello,

I have been trying to create some inventory, but no matter what I do, the stock does not reflect when I try to create a sales invoice.

I have tried with all the types of inventories, and I found that the type "Manufacture" is not working correctly. See the image attached. 
![image](https://github.com/frappe/books/assets/171364238/9851e699-0971-499d-8048-89d3e1ed3dd8)

According to the documentation, it is supposed to allow date in the "From" and "To" fields, but it does not.

This is a pretty awesome software.

I would appreciate guidance on making the inventory work with the sales invoices.

Thanks.

R.

<h2>Steps to Reproduce</h2>
Add steps to reproduce the error...

<h2>Info</h2>

**Version**: `0.21.2`
**Platform**: `win32`
**Path**: `/edit/StockMovement/New%20Stock%20Movement%2003`
**Language**: `-`
**Country**: `ie`

**Comment by ableksaju** [comment]
Hi @Zagoro ,

The "Manufacture" movement type is intended to be used for building a new item using existing stock. There might be a misunderstanding with how the "From" and "To" fields function. Unlike other movement types, "Manufacture" requires you to specify only the "From" field or the "To" field, depending on whether you're consuming or creating stock, respectively.


<img width="950" alt="Screenshot 2024-07-31 at 3 20 32 PM" src="https://github.com/user-attachments/assets/f92d1411-e1ef-457c-bdd5-13f21120b517">

**Comment by akshayitzme** [comment]
@Zagoro Do you still need help with this issue ?

**Comment by akshayitzme** [comment]
closing this cause of lack of response.
