### ISSUE TITLE
🐛 [Bug] - <Content Area too small/unreadable on my 4K monitor. No resize interface found.>

### ISSUE THREAD

**Issue by Eirikur** [frappe/books#900]
### Expected Behavior

I ran frappe-books from the command line and thought that perhaps the missing resize was a command line option. If it is, I can't discover it because -h and --help are not present. I like the look of your program very much. I'd like to use and recommend it.
--Eiríkur
-----------
Linux Mint 21 Vanessa on Ubuntu Jammy Jellyfish 22.04
Linux 5.15.0-75-generic #82-Ubuntu SMP Tue Jun 6 23:10:23 UTC 2023
Intel(R) Core(TM) i7-10700T CPU @ 2.00GHz

### FrappeBooks Version

021.2 Version is not visible anywhere on program. Had to get this number from github.

### Path or Feature name

Electron shell?

### Country

US

### Language

EN

### OS

Linux x86_64

### Additional OS Info

Linux Mint 21 Vanessa on Ubuntu Jammy Jellyfish 22.04 Linux 5.15.0-75-generic #82-Ubuntu SMP Tue Jun 6 23:10:23 UTC 2023

**Comment by ableksaju** [comment]
@Eirikur  Could you provide the resolution of your device?

**Comment by akshayitzme** [comment]
@Eirikur closing due to lack of response. Please reopen the issue with more information if it still persist
