### ISSUE TITLE
re Printing to Printer Function

### ISSUE THREAD

**Issue by Slzg** [frappe/books#902]
<h2>Description</h2>
Add some description...
Printing is only Print Preview and Save As PDF... is there a printing to Printer function? Would love to have this funciton.
<h2>Steps to Reproduce</h2>
Add steps to reproduce the error...

<h2>Info</h2>

**Version**: `0.21.2`
**Platform**: `win32`
**Path**: `/settings`
**Language**: `-`
**Country**: `kh`

**Comment by xcode-ae** [comment]
interested

**Comment by uc77** [comment]
++ Interested and keen to see if we have possibilities ahead.

**Comment by xcode-ae** [comment]
> ++ Interested and keen to see if we have possibilities ahead.

hello,
there is someone did a quick script check it out 
https://github.com/frappe/books/issues/785#issuecomment-2392243370

**Comment by akshayitzme** [comment]
Closing this as duplicate of #785

**Comment by Slzg** [comment]
Ok
