### ISSUE TITLE
Help in Frappe Books

### ISSUE THREAD

**Issue by oveeriksson** [frappe/books#910]
<h2>Description</h2>

Hi, when I try to to help from the Help link I get Hmmm… can't reach this page. 

Have tried Google Chrome and Edge but both generate this msg. 

BR, Ove 

ove.eriksson@dahai.se

<h2>Steps to Reproduce</h2>
Add steps to reproduce the error...

<h2>Info</h2>

**Version**: `0.21.2`
**Platform**: `darwin`
**Path**: `/settings`
**Language**: `English`
**Country**: `in`

**Comment by akshayitzme** [comment]
Hi @oveeriksson ,

Books Documentation has moved to a new URL. Please refer this page for the documentation [docs.frappe.io/books/introduction](https://docs.frappe.io/books/introduction)

a pull request containing the fix for the same is created here #908

**Comment by akshayitzme** [comment]
closing this as completed
