### ISSUE TITLE
"Help" and links to "Documlentation" in App are loading to an invalid web page

### ISSUE THREAD

**Issue by Tungill** [frappe/books#923]
<h2>Description</h2>
When clicking on "Help" button or on the link to documentation in app I am redirected on my web browser on a page that fails to load.

<h2>Steps to Reproduce</h2>

1. Open FrappeBooks
2. Click on "Help" / "Aide" in French on the bottom side menu
3. Wait for my web browser to load the page

<h2>Info</h2>

**Version**: `0.21.2`
**Platform**: `win32`
**Path**: `/get-started`
**Language**: `French`
**Country**: `fr`

![Frappe_Books_v6SIj8n2s5](https://github.com/user-attachments/assets/d7d53634-84aa-43a3-8b68-d32acfc063a2)
![Frappe_Books_jKagOgXWmo](https://github.com/user-attachments/assets/8791441a-3b31-4120-a078-2d8c29ee4e71)
![firefox_7LHO2YOACr](https://github.com/user-attachments/assets/5d4874f1-2b5a-4db2-bd3b-857ac475b674)

**Comment by ableksaju** [comment]
@Tungill, Books Documentation has moved to a new URL. Please refer to the updated documentation here: [docs.frappe.io/books/introduction](https://docs.frappe.io/books/introduction).

I’ve also fixed the issue in this pull request: https://github.com/frappe/books/pull/908.

**Comment by Tungill** [comment]
I am sorry I didn't see this one and I made a duplicate.
I am closing this issue then.
