### ISSUE TITLE
Frappe book the software lags alot

### ISSUE THREAD

**Issue by Camlabsmangalore** [frappe/books#928]
<h2>Description</h2>
Add some description...

<h2>Steps to Reproduce</h2>
Add steps to reproduce the error...

<h2>Info</h2>

**Version**: `0.21.1`
**Platform**: `win32`
**Path**: `/chart-of-accounts`
**Language**: `-`
**Country**: `in`

**Comment by ableksaju** [comment]
Could you please provide more details on where exactly you're experiencing the lag? So I can try reproducing it.

**Comment by akshayitzme** [comment]
@Camlabsmangalore If you are still facing this issue, please reopen it with additional context so I can try reproducing it.
