### ISSUE TITLE
Run it as a server?

### ISSUE THREAD

**Issue by dushyantk** [frappe/books#95]
How easy would it be to run this app on a server and access via IP?

**Comment by dushyantk** [comment]
I have tried:

> node start.js 
Error in sql: commit
FrappeJS server running on http://localhost:8000
Error in sql: commit
FrappeJS server running on http://localhost:8000

And then in the browser it says: Cannot GET /

**Comment by lukaskurz** [comment]
Would be interested in this too. Running accounting software on my machine does not seem very failsafe to me, I'd prefer to run something like this hosted on one of my homelab servers.

**Comment by harish2704** [comment]
This is possible . Pls See https://github.com/frappe/books/issues/159#issuecomment-657119072
