### ISSUE TITLE
🐛 [Bug] - <title>

### ISSUE THREAD

**Issue by EasternIndustries-IT** [frappe/books#950]
### Expected Behavior

App to install using apps.json
With this json doesn't work
`  {
    "url": "https://github.com/frappe/books.git",
    "branch": "v0.22.0"
  }`

### Current Behavior

getting an error during docker build
`FileNotFoundError: [Errno 2] No such file or directory: '/home/frappe/frappe-bench/apps/books/setup.py'`

### FrappeBooks Version

0.22.0

### Path or Feature name

docker build

### Country

US

### Language

EN

### OS

Linux x86_64

### Additional OS Info

ubuntu 22.04

**Comment by akshayitzme** [comment]
Hi @EasternIndustries-IT ,

Based on the description, it appears that you attempted to install Frappe Books as an application developed using the Frappe Framework. 

Frappe Books is built with Electron and Vue as System Software,  It doesn't require a Frappe instance to run. You can simply install Frappe Books by grabbing a [release](https://github.com/frappe/books/releases) that matches your operating system.
