### ISSUE TITLE
_DatabaseError: Error

### ISSUE THREAD

**Issue by ahmed-elgaza** [frappe/books#955]
<h2>Description</h2>
Add some description...

<h2>Steps to Reproduce</h2>
Add steps to reproduce the error...

<h2>Info</h2>

**Error**: _DatabaseError: Error
Could not locate the bindings file. Tried:
 → C:\Users\USER\books\node_modules\better-sqlite3\build\better_sqlite3.node
 → C:\Users\USER\books\node_modules\better-sqlite3\build\Debug\better_sqlite3.node
 → C:\Users\USER\books\node_modules\better-sqlite3\build\Release\better_sqlite3.node
 → C:\Users\USER\books\node_modules\better-sqlite3\out\Debug\better_sqlite3.node
 → C:\Users\USER\books\node_modules\better-sqlite3\Debug\better_sqlite3.node
 → C:\Users\USER\books\node_modules\better-sqlite3\out\Release\better_sqlite3.node
 → C:\Users\USER\books\node_modules\better-sqlite3\Release\better_sqlite3.node
 → C:\Users\USER\books\node_modules\better-sqlite3\build\default\better_sqlite3.node
 → C:\Users\USER\books\node_modules\better-sqlite3\compiled\16.17.1\win32\x64\better_sqlite3.node
 → C:\Users\USER\books\node_modules\better-sqlite3\addon-build\release\install-root\better_sqlite3.node
 → C:\Users\USER\books\node_modules\better-sqlite3\addon-build\debug\install-root\better_sqlite3.node
 → C:\Users\USER\books\node_modules\better-sqlite3\addon-build\default\install-root\better_sqlite3.node
 → C:\Users\USER\books\node_modules\better-sqlite3\lib\binding\node-v110-win32-x64\better_sqlite3.node_

**Stack**:
```
Error: Could not locate the bindings file. Tried:
    at Object.raw (C:\Users\USER\books\node_modules\knex\lib\knex-builder\make-knex.js:115:30)
    at Function.value (C:\Users\USER\books\node_modules\knex\lib\knex-builder\make-knex.js:91:29)
    at _DatabaseCore.connect (C:\Users\USER\books\backend\database\core.ts:97:21)
    at DatabaseManager._connect (C:\Users\USER\books\backend\database\manager.ts:46:19)
    at DatabaseManager.connectToDatabase (C:\Users\USER\books\backend\database\manager.ts:38:30)
    at DatabaseManager.createNewDatabase (C:\Users\USER\books\backend\database\manager.ts:34:23)
    at C:\Users\USER\books\main\registerIpcMainActionListeners.ts:220:16
```

**Version**: `0.22.0`
**Platform**: `win32`
**Path**: `/`
**Language**: `English`

**Comment by AbleKSaju** [comment]
Could you please give the steps for reproducing it?

**Comment by akshayitzme** [comment]
Closing this due to lack of response.
