### ISSUE TITLE
How to Update this version

### ISSUE THREAD

**Issue by Alexfieldng** [frappe/books#971]
<h2>Description</h2>
Add some description...

<h2>Steps to Reproduce</h2>
Add steps to reproduce the error...

<h2>Info</h2>

**Version**: `0.21.2`
**Platform**: `win32`
**Path**: `/`
**Language**: `-`
**Country**: `ng`

**Comment by ableksaju** [comment]
<img width="1102" alt="image" src="https://github.com/user-attachments/assets/66c0298f-3610-4076-ae04-e031dfc8fa82">

<br/>
<br/>

When using the app with an active network connection, a pop-up will notify you of any available updates, allowing you to install them easily.
