### ISSUE TITLE
🐛 [Bug] - Creating a new item via Common\Items is not listed under Inventory + POS.

### ISSUE THREAD

**Issue by uc77** [frappe/books#996]
### Expected Behavior

When creating an Item under Common > Item > New Item ; this item should  be shown both in POS app and under Inventory > Stock Moves to be able to move the item back and forth.

### Current Behavior

There is this particular issue when creating a new item under Common > Item > New Item > even when marking Purpose = Both (i.e sales + purchase) — the item is not created under inventory (i.e stock moves) and does not show up in the POS app. Instead, what you need to DO is create the item via Inventory > Stock Movement > New Item and then that item now shows up with it's respective stock in the POS app. It's peculiar this function yet this is the workaround I found.

### Steps to Reproduce

1. Go to Common > Items > (+) New Item
2. Create a test item and mark it either for sales, purchase, or both.
3. Go to POS app - you will note that it's not listed there
4. Go to Inventory > Stock Movement > New > Add Item ---- You will note that the item is not listed there.
5. Now create a new item via Stock Movement.
6. Now it's listed in POS app grid/list and also can be found under Common > Items

### FrappeBooks Version

0.23.0

### Path or Feature name

Creating a new item

### Country

EU

### Language

English

### OS

Windows 11

### Additional OS Info

MS Windows 11

**Comment by akshayitzme** [comment]
@uc77 

Have you checked the `Track Inventory` field for the Item ? 

![image](https://github.com/user-attachments/assets/7a4321c1-6502-41c5-9ae0-fdbaf9a07b15)

**Comment by uc77** [comment]
Ughh my bad. You are right ! Worked like a charm thank you mate !
