### ISSUE TITLE
💡 [Feature Request] - Built in language selector/changer from Frappe Books UI.

### ISSUE THREAD

**Issue by uc77** [frappe/books#998]
### Summary

Alot of discussion was already kicked off regarding this matter ( https://github.com/frappe/books/issues/149 & https://github.com/frappe/books/issues/140 )

In simple terms what we need is the possibility to change the UI either by a language field or by selecting region (locale). This would typically fall under settings and also could be chosen in the very beginning when setting up Frappe Books (wizard).

### What problem are you trying to solve?

Allow multiple languages ( i.e Arabic, Italian, Indian, French, Chinese, etc) 

### Basic Example

Possibility to change the UI / app display language via settings.

### Drawbacks

N/A

**Comment by ableksaju** [comment]
There is already a feature for changing languages in Frappe Books. Currently, 14 languages are available, including Arabic, French, Chinese, and more. You can access this feature by clicking Change DB in the sidebar.

<br/>

<img width="350" alt="image" src="https://github.com/user-attachments/assets/b27faf9b-7d84-4db3-b1a3-a68950edc191">

<br/>
<br/>

You can choose the language from the dropdown

<img width="373" alt="image" src="https://github.com/user-attachments/assets/bd8b63f0-b2ac-42e6-9a2d-560de4c55b02">

**Comment by uc77** [comment]
Wow thanks mate ! It was a kept tight secret then lol. I did not find it 😄

**Comment by uc77** [comment]
Closing this.
